### ISSUE TITLE
求助  nb run 启动报错

### ISSUE THREAD

**Issue by contradiction123** [CMHopeSunshine/LittlePaimon#100]
`07-07 21:37:32 [SUCCESS] nonebot | NoneBot is initializing...
07-07 21:37:32 [INFO] nonebot | Current Env: prod
07-07 21:37:32 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
07-07 21:37:33 [SUCCESS] nonebot | Succeeded to import "Paimon_Wiki"
07-07 21:37:34 [SUCCESS] nonebot | Succeeded to import "Guess_voice"
07-07 21:37:35 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
07-07 21:37:35 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
07-07 21:37:36 [SUCCESS] nonebot | Succeeded to import "random_img"
07-07 21:37:36 [SUCCESS] nonebot | Succeeded to import "order"
07-07 21:37:36 [SUCCESS] nonebot | Succeeded to import "news"
07-07 21:37:36 [SUCCESS] nonebot | Succeeded to import "paimon_help"
07-07 21:37:36 [ERROR] nonebot | Failed to import "auto_handle"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\miyuoshe\pmBot\.\bot.py", line 27, in <module>
    nonebot.load_plugins("LittlePaimon")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\miyuoshe\pmBot\.\LittlePaimon\Paimon_Plugins\__init__.py", line 23, in <module>
    load_plugins(os.path.dirname(__file__))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\miyuoshe\pmBot\.\LittlePaimon\Paimon_Plugins\auto_handle.py", line 12, in <module>
    superuser = int(list(get_driver().config.superusers)[0])
IndexError: list index out of range
07-07 21:37:37 [SUCCESS] nonebot | Succeeded to import "couplets"
07-07 21:37:37 [SUCCESS] nonebot | Succeeded to import "Paimon_Plugins"
07-07 21:37:37 [SUCCESS] nonebot | Succeeded to import "Paimon_Calendar"
07-07 21:37:41 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
07-07 21:37:41 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
07-07 21:37:41 [INFO] LittlePaimon | 派蒙机器学习聊天启用失败，mongodb尚未配置
07-07 21:37:41 [SUCCESS] nonebot | Succeeded to import "Paimon_Chat"
07-07 21:37:41 [SUCCESS] nonebot | Running NoneBot...
07-07 21:37:41 [INFO] uvicorn | Started server process [2660]
07-07 21:37:41 [INFO] uvicorn | Waiting for application startup.
07-07 21:37:41 [INFO] nonebot_plugin_apscheduler | Scheduler Started
07-07 21:37:42 [INFO] uvicorn | Application startup complete.
07-07 21:37:42 [ERROR] uvicorn | [Errno 10013] error while attempting to bind on address ('0.0.0.0', 8080): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
07-07 21:37:42 [INFO] uvicorn | Waiting for application shutdown.
07-07 21:37:42 [INFO] uvicorn | Application shutdown complete.`

**Comment by CMHopeSunshine** [comment]
如果你是看我博客教程的话，那应该是没把`.env`文件里的`dev`改成`prod`

**Comment by contradiction123** [comment]
我的错 改错文件了  改成 .env.dev了   之后又生成了一个 .env.prod 这个文件没有改
