### ISSUE TITLE
Failed to import "auto_handle"

### ISSUE THREAD

**Issue by Admsec** [CMHopeSunshine/LittlePaimon#112]
07-12 22:57:54 [ERROR] nonebot | **Failed to import "auto_handle"**
Traceback (most recent call last):
  File "D:\OneDrive\桌面\demo\nonebot2\bot.py", line 27, in <module>
    nonebot.load_plugins("LittlePaimon")
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\OneDrive\桌面\demo\nonebot2\LittlePaimon\Paimon_Plugins\__init__.py", line 5, in <module>
    load_plugins(os.path.dirname(__file__))
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\OneDrive\桌面\demo\nonebot2\LittlePaimon\Paimon_Plugins\auto_handle.py", line 12, in <module>
    superuser = int(list(get_driver().config.superusers)[0])
IndexError: list index out of range
请问这是怎么回事，我已经配置好了superuser的
![image](https://user-images.githubusercontent.com/86643414/178521700-c5a384fb-383a-42d1-b05c-b053a0f88637.png)

**Comment by Admsec** [comment]
对不起，是我自己的问题，配置名打错了，正确应该是这样
![image](https://user-images.githubusercontent.com/86643414/178522673-b0abd6ce-27fe-4b72-aa1f-916b8ad5af74.png)
