### ISSUE TITLE
添加公共ck报错

### ISSUE THREAD

**Issue by dozen6** [CMHopeSunshine/LittlePaimon#12]
[2022-04-12 17:28:43,054 派蒙绑定] INFO: Message 535085478 triggered bing_public.
[2022-04-12 17:28:43,430 派蒙绑定] ERROR: <class 'sqlite3.OperationalError'> occured when bing_public handling message 5
35085478.
[2022-04-12 17:28:43,430 派蒙绑定] ERROR: near ")": syntax error
Traceback (most recent call last):
  File "C:\Bot\LittlePaimon-Bot\LittlePaimon\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Bot\LittlePaimon-Bot\LittlePaimon\hoshino\modules\Genshin_Paimon\user_data\__init__.py", line 58, in bing_pub
lic
    await insert_public_cookie(cookie)
  File "C:\Bot\LittlePaimon-Bot\LittlePaimon\hoshino\modules\Genshin_Paimon\db_util.py", line 101, in insert_public_cook
ie
    cursor.execute('''CREATE TABLE IF NOT EXISTS public_cookies
sqlite3.OperationalError: near ")": syntax error
[2022-04-12 17:28:43,430 nonebot] INFO: Message 535085478 is ignored: Handled by Hoshino

**Comment by CMHopeSunshine** [comment]
额额db_util.py的105行`status TEXT,`不小心多写了一个逗号，删掉重启就行
