### ISSUE TITLE
米游社签到和米游币获取报错不可用

### ISSUE THREAD

**Issue by Chinzicam** [CMHopeSunshine/LittlePaimon#156]
08-04 18:53:18 [ERROR] apscheduler | Job "coin_auto_sign (trigger: cron[hour='18', minute='52'], next run at: 2022-08-05 18:52:00 CST)" raised an exception
Traceback (most recent call last):
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\czc\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete    self.run_forever()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
> File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File ".\LittlePaimon\Paimon_Info\__init__.py", line 718, in coin_auto_sign
    data = await get_coin_task.task_run()
  File ".\LittlePaimon\Paimon_Info\get_coin.py", line 99, in task_run
    im = start + '\n' + sign + '\n' + read + '\n' + like + '\n' + share
TypeError: can only concatenate str (not "NoneType") to str

米游社自动签到功能报错，但仍然在群里发送签到成功的通知，但是是昨天的签到结果

米游币自动获取也是

**Comment by CMHopeSunshine** [comment]
`米游币自动获取`存在bug暂不能用（米游币获取是可用的），`米游社自动签到`报啥错了呢，日志里只是`米游币自动获取`的报错信息

**Comment by Chinzicam** [comment]
emm之前忘记截图了。。。刚刚全部重签了一下，这次没报错，正常运行，米游社自动签到仍然是5000莫拉（今天是第四天应该是20原石）。同时，如果发送mys签到的话显示的是20石头，但实际上米游社看没效果

**Comment by Chinzicam** [comment]
![QQ截图20220804194812](https://user-images.githubusercontent.com/108013361/182839710-12662ce2-f1aa-4f38-9706-b922bbab9942.png)
米游币获取也不可用，日志里也没有报错（今天之前米游币自动获取和米游社自动签到都是正常的
