### ISSUE TITLE
nb run出现bug 无法import一些组件

### ISSUE THREAD

**Issue by YvetteVv** [CMHopeSunshine/LittlePaimon#162]
```
08-05 21:36:24 [ERROR] nonebot | Failed to import "Paimon_CloudGenshin"
    from littlepaimon_utils.files import load_json, download
ModuleNotFoundError: No module named 'littlepaimon_utils'
08-05 21:36:24 [ERROR] nonebot | Failed to import "Paimon_Plugins"
from littlepaimon_utils.files import load_json, download
ModuleNotFoundError: No module named 'littlepaimon_utils'
08-05 21:36:24 [ERROR] nonebot | Failed to import "Paimon_Info"
Traceback (most recent call last):
  File "/home/lighthouse/.local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lighthouse/bot/paimon/./bot.py", line 27, in <module>
    nonebot.load_plugins("LittlePaimon")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lighthouse/bot/paimon/./LittlePaimon/__init__.py", line 6, in <module>
```

**Comment by CMHopeSunshine** [comment]
pip install littlepaimon_utils

**Comment by YvetteVv** [comment]
> pip install littlepaimon_utils

谢谢，已经解决。现在进到UI了但是无法加载出群或者好友

**Comment by YvetteVv** [comment]
![image](https://user-images.githubusercontent.com/45150983/183145557-d0970a92-327e-4e29-97ba-58d2e901fe8d.png)

**Comment by CMHopeSunshine** [comment]
登录账号之后需要重启一次bot

**Comment by YvetteVv** [comment]
已解决
