### ISSUE TITLE
几乎所有的插件都不能import

### ISSUE THREAD

**Issue by nimeng1299** [CMHopeSunshine/LittlePaimon#173]
几乎每个插件都不能正常的启动，尝试过把别人能正常运行的文件移植过来。
pip install littlepaimon_utils也试过了
pip list安装的包和别人都是一样的。
不过报错也能启动
启动后能进管理面板和接受信息，但是无法发送.

![e52d3625f518c12435f6e52a4bac959](https://user-images.githubusercontent.com/92239668/184134799-ded2a751-9116-4c53-b3c5-6511b99a2eda.jpg)
![a10ca8e952e871ae30da7de50214884](https://user-images.githubusercontent.com/92239668/184134841-4f6df1e4-1631-4dcb-aae6-02a2c553f82a.png)
![e52d3625f518c12435f6e52a4bac959](https://user-images.githubusercontent.com/92239668/184134855-bfd8a2ac-6ff7-4586-a550-0fe4755ec176.jpg)

**Comment by CMHopeSunshine** [comment]
有没有可能是littlepaimon_utils没装在nb用的py环境里呢（如果你使用了虚拟环境或者存在多个python版本的话）

**Comment by nimeng1299** [comment]
![-36a17a196286663d](https://user-images.githubusercontent.com/92239668/184273367-04040f56-5419-438d-a39f-30d4755bdc7b.jpg)
重装了几次终于好了，现在报错这个。群里能自动回复但私聊就没反应，只能收到信息

**Comment by Cathgao** [comment]
同样问题，很多的插件都说不能import，还没解决

**Comment by CMHopeSunshine** [comment]
> 同样问题，很多的插件都说不能import，还没解决

缺什么依赖就装什么

**Comment by Mrxiaobbbaiii** [comment]
08-15 17:30:37 [WARNING] src | 派蒙机器学习启用失败，未配置mongodb连接url，如无
需该功能，可忽略
08-15 17:30:37 [SUCCESS] nonebot | Succeeded to import "Paimon_Chat"
08-15 17:30:37 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apschedul
er"
08-15 17:30:37 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
08-15 17:30:37 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
08-15 17:30:38 [SUCCESS] nonebot | Succeeded to import "Paimon_Wiki"
08-15 17:30:38 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
08-15 17:30:38 [ERROR] nonebot | Failed to import "auto_handle"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\PaimonBot\Nonebot2\bot.py", line 27, in <
module>
    nonebot.load_plugins("src/plugins/LittlePaimon")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\import
lib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\PaimonBot\Nonebot2\src\plugins\LittlePaim
on\Paimon_Plugins\__init__.py", line 5, in <module>
    load_plugins(os.path.dirname(__file__))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\import
lib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-p
ackages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\PaimonBot\Nonebot2\src\plugins\LittlePaim
on\Paimon_Plugins\auto_handle.py", line 12, in <module>
    superuser = int(list(get_driver().config.superusers)[0])
IndexError: list index out of range
求助QAQ
