### ISSUE TITLE
mys签到等问题

### ISSUE THREAD

**Issue by Chinzicam** [CMHopeSunshine/LittlePaimon#200]
自动签到和手动mys签到都无效
![image](https://user-images.githubusercontent.com/108013361/186806128-f1edc637-05e3-47d9-91f1-8c9db6135607.png)
不会在QQ群通知，日志也没报错

ysa和更新角色信息失败，估计都是因为没有科莱图片原因😣还是说已经更新图片资源了
![image](https://user-images.githubusercontent.com/108013361/186807658-5eccfac0-f5ad-4948-9f02-829fb629eaa1.png)
这个bot分支是指？

**Comment by CMHopeSunshine** [comment]
签到确认已炸，目前尚未有稳定成功的修复方法，Bot分支是[这里](https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot)，默认分支不再更新须弥相关东西

**Comment by Chinzicam** [comment]
> 签到确认已炸，目前尚未有稳定成功的修复方法，Bot分支是[这里](https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot)，默认分支不再更新须弥相关东西

ok，了解了😘

**Comment by Chinzicam** [comment]
> 签到确认已炸，目前尚未有稳定成功的修复方法，Bot分支是[这里](https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot)，默认分支不再更新须弥相关东西

08-26 11:29:17 [ERROR] nonebot | Failed to import "alias_manager"
Traceback (most recent call last):
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\czc\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 26, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\__init__.py", line 43, in <module>
    load_plugins(str(Path(__file__).parent / 'manager'))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\manager\alias_manager\__init__.py", line 8, in <module>
    from .handler import handle, get_id
  File ".\LittlePaimon\manager\alias_manager\handler.py", line 4, in <module>
    from .parser import parse_msg
  File ".\LittlePaimon\manager\alias_manager\parser.py", line 2, in <module>
    from expandvars import expand, ExpandvarsException
ModuleNotFoundError: No module named 'expandvars'
08-26 11:29:17 [WARNING] LittlePaimon | [插件管理器]无法读取配置文件，请检查是否已将config/paimon_config_default.yml复制为config/paimon_config.yml

这个报错是指？按着这个做的
![image](https://user-images.githubusercontent.com/108013361/186812573-b70a79ec-2528-4e96-a217-9de3da5dce82.png)

**Comment by Chinzicam** [comment]
貌似没有paimon_config.yml文件

**Comment by Chinzicam** [comment]
> 签到确认已炸，目前尚未有稳定成功的修复方法，Bot分支是[这里](https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot)，默认分支不再更新须弥相关东西

啊这...我的锅，找到了且paimon_config.yml已复制
但是新的报错
08-26 11:46:10 [ERROR] nonebot | Failed to import "alias_manager"
Traceback (most recent call last):
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\czc\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 26, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\__init__.py", line 43, in <module>
    load_plugins(str(Path(__file__).parent / 'manager'))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\manager\alias_manager\__init__.py", line 8, in <module>
    from .handler import handle, get_id
  File ".\LittlePaimon\manager\alias_manager\handler.py", line 4, in <module>
    from .parser import parse_msg
  File ".\LittlePaimon\manager\alias_manager\parser.py", line 2, in <module>
    from expandvars import expand, ExpandvarsException
ModuleNotFoundError: No module named 'expandvars'

**Comment by CMHopeSunshine** [comment]
`poetry run pip install expandvars`

**Comment by Chinzicam** [comment]
一样
08-26 13:10:58 [ERROR] nonebot | Failed to import "alias_manager"
Traceback (most recent call last):
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\czc\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\czc\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 26, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "c:\users\czc\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\__init__.py", line 43, in <module>
    load_plugins(str(Path(__file__).parent / 'manager'))
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\users\czc\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\czc\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\manager\alias_manager\__init__.py", line 8, in <module>
    from .handler import handle, get_id
  File ".\LittlePaimon\manager\alias_manager\handler.py", line 4, in <module>
    from .parser import parse_msg
  File ".\LittlePaimon\manager\alias_manager\parser.py", line 2, in <module>
    from expandvars import expand, ExpandvarsException
ModuleNotFoundError: No module named 'expandvars'

![image](https://user-images.githubusercontent.com/108013361/186826871-13f230fa-cf2e-401e-b520-ce970f889455.png)

**Comment by Chinzicam** [comment]
> `poetry run pip install expandvars`

好怪，刚刚把服务器上的也更新了下，第一次加载机器人也报了这个错误，然后由于资源下载太慢失败了,重新启动了一下，这个报错就无了......🤔
