### ISSUE TITLE
【bot分支】最新版bug

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#201]
08-26 19:00:00 [ERROR] apscheduler | Job "check_note (trigger: cron[minute='*/16'], next run at: 2022-08-26 19:16:00 CST)" raised an exception
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\nonebot\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File ".\LittlePaimon\plugins\Paimon_DailyNote\handler.py", line 78, in check_note    subs = await DailyNoteSub.all()
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\tortoise\models.py", line 1277, in all
    db = using_db or cls._choose_db()
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\tortoise\models.py", line 1033, in _choose_db
    db = router.db_for_read(cls)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\tortoise\router.py", line 36, in db_for_read
    return self._db_route(model, "db_for_read")
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\tortoise\router.py", line 31, in _db_route
    return connections.get(self._router_func(model, action))
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\tortoise\router.py", line 18, in _router_func
    for r in self._routers:
TypeError: 'NoneType' object is not iterable

**Comment by forchannot** [comment]
此外，发送ssbq钱币提醒仍然提示的是树脂
![image](https://user-images.githubusercontent.com/100580891/186890097-1ed82e08-c055-4948-a0d0-a1564e3df269.png)

**Comment by CMHopeSunshine** [comment]
已修

**Comment by forchannot** [comment]
> 已修

好像没完全修复
![image](https://user-images.githubusercontent.com/100580891/186892573-0d12c0f7-f819-4521-bac8-54595556aef5.png)

**Comment by CMHopeSunshine** [comment]
修复前的命令将2300绑定到树脂了，重新设一下树脂数就行

**Comment by forchannot** [comment]
> 修复前的命令将2300绑定到树脂了，重新设一下树脂数就行

好的
