### ISSUE TITLE
群成员多次 猜语音后,提示 "当前已经有一个游戏正在进行中啦！"

### ISSUE THREAD

**Issue by fangyuanshisan** [CMHopeSunshine/LittlePaimon#205]
日志报错
![image](https://user-images.githubusercontent.com/3401189/187017991-a7104752-873a-4241-9a7b-7cf5758e2030.png)

**Comment by fangyuanshisan** [comment]
老板这个什么时候更新

**Comment by fangyuanshisan** [comment]
这个有临时解决办法嘛!

**Comment by CMHopeSunshine** [comment]
我无论怎么试都重现不了这个问题，你能再发一下报错log吗，完整一点

**Comment by fangyuanshisan** [comment]
08-29 13:48:37 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -869040138 from 2644312075@[群:818679140] "原神猜语音"
08-29 13:48:37 [INFO] nonebot | Event will be handled by <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False>
08-29 13:48:38 [INFO] nonebot_plugin_gocqhttp | [1656383945] 发送群 喵呜喵呜的秘密基地（天命难违微店在售）(818679140) 的消息: [{"type":  ... (-1154199712)
08-29 13:48:39 [INFO] nonebot_plugin_gocqhttp | [1656383945] 发送群 喵呜喵呜的秘密基地（天命难违微店在售）(818679140) 的消息: [{"type":  ... (626055875)
08-29 13:48:39 [INFO] nonebot | Matcher <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False> running complete
08-29 13:48:45 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: 凝光 (1381493333)
08-29 13:48:45 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 1381493333 from 2644312075@[群:818679140] "凝光"
08-29 13:48:49 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: [CQ:image,file=31d2771924c0f795388f34cdf16a16ea.image,subType=1,url=https://gchat.qpic.cn/gchatpic_new/2644312075/818679140-2496985158-31D2771924C0F795388F34CDF16A16EA/0?term=2] (-882983953)
08-29 13:48:49 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -882983953 from 2644312075@[群:818679140] "[CQ:image,file=31d2771924c0f795388f34cdf16a16ea.image,subType=1,url=https://gchat.qpic.cn/gchatpic_new/2644312075/818679140-2496985158-31D2771924C0F795388F34CDF16A16EA/0?term=2]"
08-29 13:48:57 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 那个那个 (-1134982279)
08-29 13:48:57 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -1134982279 from 3089086977@[群:818679140] "那个那个"
08-29 13:48:59 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 753309416 from 3089086977@[群:818679140] "修女"
08-29 13:48:59 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 修女 (753309416)
08-29 13:48:59 [INFO] nonebot | Event will be handled by <Matcher from LittlePaimon.plugins.Genshin_Voice.handler, type=message, priority=1, temp=True>
08-29 13:48:59 [INFO] LittlePaimon | [原神猜语音]➤群818679140猜语音游戏结束，答案为罗莎莉亚，由咩啊（宝贝有事别找我，不然铁定暗恋我）猜对
08-29 13:48:59 [INFO] nonebot_plugin_gocqhttp | [1656383945] 发送群 喵呜喵呜的秘密基地（天命难违微店在售）(818679140) 的消息: [{"type":  ... (1541514878)
08-29 13:48:59 [INFO] nonebot | Matcher <Matcher from LittlePaimon.plugins.Genshin_Voice.handler, type=message, priority=1, temp=True> running complete
08-29 13:49:01 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: 焯修女 (1836877853)
08-29 13:49:01 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 1836877853 from 2644312075@[群:818679140] "焯修女"
08-29 13:49:06 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: 罗莎莉亚 (444315787)
08-29 13:49:06 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 444315787 from 2644312075@[群:818679140] "罗莎莉亚"
08-29 13:49:12 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 想不起名字 (-2089621199)
08-29 13:49:12 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -2089621199 from 3089086977@[群:818679140] "想不起名字"
08-29 13:49:13 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: 没养 (-193603161)
08-29 13:49:13 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -193603161 from 2644312075@[群:818679140] "没养"
08-29 13:49:14 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 一瞬间 (1779518468)
08-29 13:49:14 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 1779518468 from 3089086977@[群:818679140] "一瞬间"
08-29 13:49:17 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 脑子失忆 (488012946)
08-29 13:49:17 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 488012946 from 3089086977@[群:818679140] "脑子失忆"
08-29 13:49:24 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 抹茶(1442926755) 的消息: 我甚至没这个角色 (-2078331608)
08-29 13:49:24 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -2078331608 from 1442926755@[群:818679140] "我甚至没这个角色"
08-29 13:49:24 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: 脑子失忆+1 (-216523330)
08-29 13:49:24 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -216523330 from 2644312075@[群:818679140] "脑子失忆+1"
08-29 13:49:31 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: 我都满命了。 (1671888943)
08-29 13:49:31 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 1671888943 from 2644312075@[群:818679140] "我都满命了。"
08-29 13:49:39 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: 溢出来三个。 (346042553)
08-29 13:49:39 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 346042553 from 2644312075@[群:818679140] "溢出来三个。"
08-29 13:49:41 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 抹茶(1442926755) 的消息: 我角色很少 (1952954716)
08-29 13:49:41 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 1952954716 from 1442926755@[群:818679140] "我角色很少"
08-29 13:49:53 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: 原神猜语音 (56658378)
08-29 13:49:53 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 56658378 from 2644312075@[群:818679140] "原神猜语音"
08-29 13:49:53 [INFO] nonebot | Event will be handled by <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False>
08-29 13:49:53 [INFO] nonebot | Matcher <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False> running complete
08-29 13:49:53 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False> failed.
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/root/miaowushenshou/miaowushenshou/./LittlePaimon/plugins/Genshin_Voice/__init__.py", line 63, in _
    result = await game.start()
  File "/root/miaowushenshou/miaowushenshou/./LittlePaimon/plugins/Genshin_Voice/handler.py", line 38, in start
    create_guess_matcher(self.group_id, voice.character, self.game_time)
  File "/root/miaowushenshou/miaowushenshou/./LittlePaimon/plugins/Genshin_Voice/handler.py", line 91, in create_guess_matcher
    re_str = '|'.join(alias_list)
TypeError: can only join an iterable
08-29 13:50:00 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: 原神猜语音 (-1704339344)
08-29 13:50:00 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -1704339344 from 2644312075@[群:818679140] "原神猜语音"
08-29 13:50:00 [INFO] nonebot | Event will be handled by <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False>
08-29 13:50:00 [INFO] nonebot_plugin_gocqhttp | [1656383945] 发送群 喵呜喵呜的秘密基地（天命难违微店在售）(818679140) 的消息: [{"type":  ... (-311498522)
08-29 13:50:00 [INFO] nonebot_plugin_gocqhttp | [1656383945] 发送群 喵呜喵呜的秘密基地（天命难违微店在售）(818679140) 的消息: [{"type":  ... (1930067269)
08-29 13:50:00 [INFO] nonebot | Matcher <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False> running complete
08-29 13:50:07 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: ？ (67980755)
08-29 13:50:07 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 67980755 from 2644312075@[群:818679140] "？"
08-29 13:50:08 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 玩了 (-1660674967)
08-29 13:50:08 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -1660674967 from 3089086977@[群:818679140] "玩了"
08-29 13:50:11 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 完了 (-368890625)
08-29 13:50:11 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -368890625 from 3089086977@[群:818679140] "完了"
08-29 13:50:12 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 祖安ba(2644312075) 的消息: [CQ:image,file=1bfe9d4c366b01c2b7ea01aa5cd2c4e4.image,subType=1,url=https://gchat.qpic.cn/gchatpic_new/2644312075/818679140-2920450184-1BFE9D4C366B01C2B7EA01AA5CD2C4E4/0?term=2] (2059153774)
08-29 13:50:12 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 2059153774 from 2644312075@[群:818679140] "[CQ:image,file=1bfe9d4c366b01c2b7ea01aa5cd2c4e4.image,subType=1,url=https://gchat.qpic.cn/gchatpic_new/2644312075/818679140-2920450184-1BFE9D4C366B01C2B7EA01AA5CD2C4E4/0?term=2]"
08-29 13:50:20 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 它又卡bug了 (230359544)
08-29 13:50:20 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 230359544 from 3089086977@[群:818679140] "它又卡bug了"
08-29 13:50:29 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 原神猜语音 (1598745247)
08-29 13:50:29 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 1598745247 from 3089086977@[群:818679140] "原神猜语音"
08-29 13:50:29 [INFO] nonebot | Event will be handled by <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False>
08-29 13:50:29 [INFO] nonebot_plugin_gocqhttp | [1656383945] 发送群 喵呜喵呜的秘密基地（天命难违微店在售）(818679140) 的消息: [{"type":  ... (676190729)
08-29 13:50:30 [INFO] nonebot_plugin_gocqhttp | [1656383945] 发送群 喵呜喵呜的秘密基地（天命难违微店在售）(818679140) 的消息: [{"type":  ... (-1320907853)
08-29 13:50:30 [INFO] nonebot | Matcher <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False> running complete
08-29 13:50:36 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: [CQ:at,qq=1147221290] (-968639707)
08-29 13:50:36 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message -968639707 from 3089086977@[群:818679140] "[CQ:at,qq=1147221290]"
08-29 13:50:39 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: [CQ:image,file=885abcfe92875286cb46b4cb316de3e6.image,subType=1,url=https://gchat.qpic.cn/gchatpic_new/3089086977/818679140-2594870966-885ABCFE92875286CB46B4CB316DE3E6/0?term=2] (1478962822)
08-29 13:50:39 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 1478962822 from 3089086977@[群:818679140] "[CQ:image,file=885abcfe92875286cb46b4cb316de3e6.image,subType=1,url=https://gchat.qpic.cn/gchatpic_new/3089086977/818679140-2594870966-885ABCFE92875286CB46B4CB316DE3E6/0?term=2]"
08-29 13:50:46 [INFO] nonebot_plugin_gocqhttp | [1656383945] 收到群 喵呜喵呜的秘密基地（(818679140) 内 咩啊（宝贝有事别找我，不然铁定暗恋我）(3089086977) 的消息: 魈说卡bug了 (790634000)
08-29 13:50:46 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 790634000 from 3089086977@[群:818679140] "魈说卡bug了"

**Comment by fangyuanshisan** [comment]
日志太长了,我截取了一下, 群里玩家在这条信息发送命令后, 08-29 13:49:53 [SUCCESS] nonebot | ONEBOT V11 1656383945 | [message.group.normal]: Message 56658378 from 2644312075@[群:818679140] "原神猜语音", 就有了这个报错.很奇怪.前面的都是正常使用,好像是突然报错

**Comment by fangyuanshisan** [comment]
刚刚人为造了一个场景,.有A和B两个群,A群发送"原神猜语音", 紧接着B群发送"原神猜语音",B群回答后,B群结束游戏. A群还是在游戏状态中. 后续一直就在游戏中,除非重启. 我再看看有没有其他场景会这样

**Comment by CMHopeSunshine** [comment]
大概知道问题所在了，随机到了主角的语音产生了bug，明天修

**Comment by fangyuanshisan** [comment]
这个功能太受欢迎了,他们可太喜欢了,天天逼着我问!!! 我是被迫的!! 作者大大催更了!!

**Comment by fangyuanshisan** [comment]
09-03 10:52:45 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.plugins.Genshin_Voice, type=message, priority=12, temp=False> failed.
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/miaowushenshou-fbvSxiaS-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/root/miaowushenshou/miaowushenshou/./LittlePaimon/plugins/Genshin_Voice/__init__.py", line 63, in _
    result = await game.start()
  File "/root/miaowushenshou/miaowushenshou/./LittlePaimon/plugins/Genshin_Voice/handler.py", line 38, in start
    create_guess_matcher(self.group_id, voice.character, self.game_time)
  File "/root/miaowushenshou/miaowushenshou/./LittlePaimon/plugins/Genshin_Voice/handler.py", line 91, in create_guess_matcher
    re_str = '|'.join(alias_list)
TypeError: can only join an iterable
09-03 10:52:52 [WARNING] nonebot_plugin_gocqhttp | [1656383945] 语音文件 8DF5C0BFD0EA6BE434739B962A61F7BD.amr 下载失败: Get "http://grouptalk.c2c.qq.com": EOF

**Comment by fangyuanshisan** [comment]
新的报错 也会导致游戏进行中

**Comment by CMHopeSunshine** [comment]
这是同一个报错，已修，试试

**Comment by fangyuanshisan** [comment]
> 这是同一个报错，已修，试试

辛苦了!!除了有次空目前到下午没什么问题! 催更进群欢迎!!
