### ISSUE TITLE
查看抽卡记录报错

### ISSUE THREAD

**Issue by zuixiaoxiao** [CMHopeSunshine/LittlePaimon#215]
[ERROR] nonebot | Running matcher <Matcher from LittlePaimon.plugins.Paimon_Gacha_Log, type=message, priority=12, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\原神机器人\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\原神机器人\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\原神机器人\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\原神机器人\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\原神机器人\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\原神机器人\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\原神机器人\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\原神机器人\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\原神机器人\venv\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "D:\原神机器人\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "D:\原神机器人\venv\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "D:\原神机器人\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\原神机器人\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\原神机器人\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\原神机器人\venv\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\原神机器人\venv\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "D:\原神机器人\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File ".\LittlePaimon\plugins\Paimon_Gacha_Log\__init__.py", line 112, in get_ckjl
    gacha_img = await get_gacha_log_img(gacha_data, pool_type)
  File ".\LittlePaimon\plugins\Paimon_Gacha_Log\get_img.py", line 131, in get_gacha_log_img
    p_img = await draw_gacha_log(pd)
  File ".\LittlePaimon\plugins\Paimon_Gacha_Log\get_img.py", line 60, in draw_gacha_log
    top = Image.open(res_path / 'player_card' / 'gacha_log_top.png')
  File "D:\原神机器人\venv\lib\site-packages\PIL\Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\原神机器人\\Nonebot2\\resources\\LittlePaimon\\player_card\\gacha_log_top.png'

**Comment by CMHopeSunshine** [comment]
请更新至最新代码，最新版本不再需要抽卡链接，只需要cookie就可以随时更新抽卡记录

**Comment by zuixiaoxiao** [comment]
> 

(venv) PS D:\原神机器人\Nonebot2> cd LittlePaimon
(venv) PS D:\原神机器人\Nonebot2\LittlePaimon> git pull
Already up to date.
(venv) PS D:\原神机器人\Nonebot2\LittlePaimon>
emm

**Comment by zuixiaoxiao** [comment]
> 请更新至最新代码，最新版本不再需要抽卡链接，只需要cookie就可以随时更新抽卡记录

(venv) PS D:\原神机器人\Nonebot2> cd LittlePaimon
(venv) PS D:\原神机器人\Nonebot2\LittlePaimon> git pull
Already up to date.
(venv) PS D:\原神机器人\Nonebot2\LittlePaimon>
emm

**Comment by CMHopeSunshine** [comment]
是旧分支版本吗，重新部署新分支（Bot分支）版本吧

**Comment by zuixiaoxiao** [comment]
> 是旧分支版本吗，重新部署新分支（Bot分支）版本吧

我是旧迁新，应该是成功了吧...
![image](https://user-images.githubusercontent.com/108536651/187497666-0db95ee2-b573-496d-b6f9-2dc6cb97739a.png)
![image](https://user-images.githubusercontent.com/108536651/187498707-0b9e0d7d-c20c-42bf-9f1f-0f5641fa4c98.png)

**Comment by zuixiaoxiao** [comment]
> > 是旧分支版本吗，重新部署新分支（Bot分支）版本吧
> 
> 我是旧迁新，应该是成功了吧... ![image](https://user-images.githubusercontent.com/108536651/187497666-0db95ee2-b573-496d-b6f9-2dc6cb97739a.png) ![image](https://user-images.githubusercontent.com/108536651/187497766-19e51938-498f-48fc-b322-1f9b0e1f3828.png)

![image](https://user-images.githubusercontent.com/108536651/187498153-48eb793c-9cd0-4839-8c38-7fe9a6f037ca.png)

**Comment by CMHopeSunshine** [comment]
emm是没错，但是报错那里的代码还是29号之前的版本，抽卡记录分析是在29号晚上改的

**Comment by zuixiaoxiao** [comment]
> emm是没错，但是报错那里的代码还是29号之前的版本，抽卡记录分析是在29号晚上改的

emm，我试试看重新下bot分支，重新迁一下

**Comment by zuixiaoxiao** [comment]
OK了重新下迁，指令表有出现更新抽卡信息的了
