### ISSUE TITLE
大大救命，重装新版派蒙就报这个错

### ISSUE THREAD

**Issue by zuixiaoxiao** [CMHopeSunshine/LittlePaimon#225]
原本是旧迁新但更新有问题就打算重装结果就这样了

09-02 18:03:08 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
09-02 18:03:08 [INFO] nonebot_plugin_htmlrender | 正在安装 chromium
09-02 18:03:08 [INFO] nonebot_plugin_htmlrender | 正在安装依赖
Failed to install browsers
Error: Failed to download Chromium 104.0.5112.48 (playwright build v1015), caused by
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:727:12)
09-02 18:03:11 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
09-02 18:03:11 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 38, in init
    _browser = await launch_browser(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 55, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\async_api\_generated.py", line 11424, in launch
    await self._impl_obj.launch(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\_impl\_connection.py", line 369, in wrap_api_call
    return await cb()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1015\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 59, in get_browser
    return _browser or await init(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 41, in init
    _browser = await launch_browser(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 55, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\async_api\_generated.py", line 11424, in launch
    await self._impl_obj.launch(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\_impl\_connection.py", line 369, in wrap_api_call
    return await cb()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1015\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

09-02 18:03:11 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by CMHopeSunshine** [comment]
它已经告诉你怎么办了，playwright install

**Comment by zuixiaoxiao** [comment]
> 它已经告诉你怎么办了，playwright install

![image](https://user-images.githubusercontent.com/108536651/188120127-ba2a57d7-0ccc-4bf8-bd39-8a81e9df373c.png)
还是报错

**Comment by zuixiaoxiao** [comment]
PS D:\LittlePaimon\LittlePaimon> playwright install
Failed to install browsers
Error: Failed to download Chromium 104.0.5112.48 (playwright build v1015), caused by
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:727:12)
PS D:\LittlePaimon\LittlePaimon> poetry shell
c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Virtual environment already activated: C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-gtKgcIc1-py3.8
PS D:\LittlePaimon\LittlePaimon> nb run
09-02 20:03:48 [SUCCESS] nonebot | NoneBot is initializing...
09-02 20:03:48 [INFO] nonebot | Current Env: prod
09-02 20:03:48 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
09-02 20:03:49 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
09-02 20:03:49 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets"
09-02 20:03:50 [SUCCESS] nonebot | Succeeded to import "alias_manager"
09-02 20:03:50 [SUCCESS] nonebot | Succeeded to import "database_manager"
09-02 20:03:52 [SUCCESS] nonebot | Succeeded to import "plugin_manager"
09-02 20:03:52 [SUCCESS] nonebot | Succeeded to import "Paimon_Bind"
09-02 20:03:53 [SUCCESS] nonebot | Succeeded to import "Paimon_DailyNote"
09-02 20:03:53 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
09-02 20:03:53 [SUCCESS] nonebot | Succeeded to import "Genshin_Calendar"
09-02 20:03:53 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
09-02 20:03:53 [SUCCESS] nonebot | Succeeded to import "Paimon_MonthInfo"
09-02 20:03:53 [SUCCESS] nonebot | Succeeded to import "Genshin_AIVoice"
09-02 20:03:54 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
09-02 20:03:55 [SUCCESS] nonebot | Succeeded to import "Paimon_Wiki"
09-02 20:03:55 [SUCCESS] nonebot | Succeeded to import "Genshin_Voice"
09-02 20:03:56 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
09-02 20:03:56 [SUCCESS] nonebot | Succeeded to import "news60s"
09-02 20:03:57 [SUCCESS] nonebot | Succeeded to import "Paimon_Autobbs"
09-02 20:03:57 [SUCCESS] nonebot | Succeeded to import "LittlePaimon"
09-02 20:03:57 [SUCCESS] nonebot | Running NoneBot...
09-02 20:03:57 [INFO] uvicorn | Started server process [14240]
09-02 20:03:57 [INFO] uvicorn | Waiting for application startup.
09-02 20:03:57 [INFO] nonebot_plugin_apscheduler | Scheduler Started
09-02 20:03:57 [INFO] LittlePaimon |
██╗     ██╗████████╗████████╗██╗     ███████╗  ██████╗  █████╗ ██╗███╗   ███╗ ██████╗ ███╗   ██╗
██║     ██║╚══██╔══╝╚══██╔══╝██║     ██╔════╝  ██╔══██╗██╔══██╗██║████╗ ████║██╔═══██╗████╗  ██║
██║     ██║   ██║      ██║   ██║     █████╗    ██████╔╝███████║██║██╔████╔██║██║   ██║██╔██╗ ██║
██║     ██║   ██║      ██║   ██║     ██╔══╝    ██╔═══╝ ██╔══██║██║██║╚██╔╝██║██║   ██║██║╚██╗██║
███████╗██║   ██║      ██║   ███████╗███████╗  ██║     ██║  ██║██║██║ ╚═╝ ██║╚██████╔╝██║ ╚████║
╚══════╝╚═╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝  ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
09-02 20:03:57 [SUCCESS] LittlePaimon | [数据库]连接成功
09-02 20:03:58 [INFO] LittlePaimon | [原神Cookie]启用CookieWeb成功，地址http://127.0.0.1:13579/LittlePaimon/cookie
09-02 20:03:58 [INFO] LittlePaimon | [资源检查]开始检查资源
09-02 20:03:59 [INFO] LittlePaimon | [资源检查]资源完好，无需下载
09-02 20:04:00 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
09-02 20:04:01 [INFO] nonebot_plugin_htmlrender | 正在安装 chromium
09-02 20:04:01 [INFO] nonebot_plugin_htmlrender | 正在安装依赖
Failed to install browsers
Error: Failed to download Chromium 104.0.5112.48 (playwright build v1015), caused by
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:727:12)
09-02 20:04:04 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
09-02 20:04:04 [ERROR] uvicorn | Traceback (most recent call last):

**Comment by zuixiaoxiao** [comment]
> 它已经告诉你怎么办了，playwright install

还是报错啊，大大，菜菜，捞捞

**Comment by CMHopeSunshine** [comment]
关掉代理

**Comment by zuixiaoxiao** [comment]
> 关掉代理

emm，不懂

**Comment by CMHopeSunshine** [comment]
也就是vpn、梯子、科学上网的东西

**Comment by zuixiaoxiao** [comment]
> 也就是vpn、梯子、科学上网的东西

emm，应该没有啊，加速器也就个上Git的
![image](https://user-images.githubusercontent.com/108536651/188176046-8bb8f645-2fbd-473d-8ad1-2eae4c94f23e.png)
之前倒是下了Google  Chrome

**Comment by ljx-code** [comment]
在虚拟环境下使用 yum install chromium 或者你环境里安装的其他指令安装chromium就能解决

**Comment by ljx-code** [comment]
你的虚拟环境怎么没启动？

**Comment by zuixiaoxiao** [comment]
> 你的虚拟环境怎么没启动？

谢谢提议，我重置电脑后可以了
