### ISSUE TITLE
更新角色信息和ysd命令报错 

### ISSUE THREAD

**Issue by Chinzicam** [CMHopeSunshine/LittlePaimon#230]
通过查询聊天记录，晚上7点还好好，9点钟左右突然报错，以为是正常抽风过会就好，但别人的派蒙正常
**更新失败，错误信息：get() got an unexpected keyword argument 'follow_redirects'**
![YW8SG B1J3%5Q`73 D2P @F](https://user-images.githubusercontent.com/108013361/188663796-f142bfb3-6688-4ef1-ad84-f3fede286760.png)

09-06 22:34:00 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.plug
ins.Paimon_Info, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File ".\LittlePaimon\utils\api.py", line 423, in get_enka_data
    resp = await aiorequests.get(url=url, headers={'User-Agent': 'LittlePaimon/3
.0'}, follow_redirects=True)
  File ".\LittlePaimon\utils\requests.py", line 29, in get
    return await client.get(url,
TypeError: get() got an unexpected keyword argument 'follow_redirects'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.
py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.
py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in ru
n_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in
run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asynci
o\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asynci
o\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asynci
o\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asynci
o\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asynci
o\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asynci
o\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\nonebot\message.py", line 146, in _check_m
atcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\nonebot\message.py", line 196, in _run_mat
cher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 672, in
 run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 639, in
 simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-OQxuOWGH-py3.8\lib\site-packages\nonebot\dependencies\__init__.py", line 92
, in __call__
    return await self.call(**values)
  File ".\LittlePaimon\plugins\Paimon_Info\__init__.py", line 220, in _
    character_info = await gim.get_character(name=character, data_source='enka')

  File ".\LittlePaimon\utils\genshin.py", line 174, in get_character
    await self.update_from_enka()
  File ".\LittlePaimon\utils\genshin.py", line 65, in update_from_enka
    data = await get_enka_data(self.uid)
  File ".\LittlePaimon\utils\api.py", line 429, in get_enka_data
    resp = await aiorequests.get(url=url, headers={'User-Agent': 'LittlePaimon/3
.0'}, follow_redirects=True)
  File ".\LittlePaimon\utils\requests.py", line 29, in get
    return await client.get(url,
TypeError: get() got an unexpected keyword argument 'follow_redirects'

**Comment by CMHopeSunshine** [comment]
升级httpx版本，命令`poetry run pip install httpx --upgrade`，应该是装其他插件了吧，其他插件把httpx降级了

**Comment by Chinzicam** [comment]
> 

啊这，确实是🥲装了个文心ai画画的插件。已解决，谢谢大佬🥵
