### ISSUE TITLE
emm，刚更新重启就报错了

### ISSUE THREAD

**Issue by zuixiaoxiao** [CMHopeSunshine/LittlePaimon#237]
Traceback (most recent call last):
  File "D:\LittlePaimon\LittlePaimon\.\LittlePaimon\plugins\Learning_Chat\models.py", line 8, in <module>
    import jieba_fast.analyse as jieba_analyse
ModuleNotFoundError: No module named 'jieba_fast'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\LittlePaimon\LittlePaimon\.\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\LittlePaimon\LittlePaimon\.\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-aleb-Eof-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\LittlePaimon\LittlePaimon\.\LittlePaimon\plugins\Learning_Chat\__init__.py", line 18, in <module>
    from .models import LearningChat
  File "D:\LittlePaimon\LittlePaimon\.\LittlePaimon\plugins\Learning_Chat\models.py", line 10, in <module>
    import jieba.analyse as jieba_analyse
ModuleNotFoundError: No module named 'jieba'

**Comment by zuixiaoxiao** [comment]
不知道什么鬼

**Comment by CMHopeSunshine** [comment]
`poetry install`

**Comment by zuixiaoxiao** [comment]
> `poetry install`

OK了，谢谢作者
