### ISSUE TITLE
无法更新，无论是git pull命令或者是at机器人 更新

### ISSUE THREAD

**Issue by Mr233sir** [CMHopeSunshine/LittlePaimon#256]
现在群友只要有多莉就没法更新角色信息
![QQ图片20220919173021](https://user-images.githubusercontent.com/30330282/190989589-6fa27c23-4acb-4d6c-9435-ecb3d314256d.png)

**Comment by CMHopeSunshine** [comment]
参考[链接](https://blog.csdn.net/u014163312/article/details/106341433/)

**Comment by ljx-code** [comment]
> 现在群友只要有多莉就没法更新角色信息 ![QQ图片20220919173021](https://user-images.githubusercontent.com/30330282/190989589-6fa27c23-4acb-4d6c-9435-ecb3d314256d.png)

因为之前bot不是主分支，之前作者大大把bot变成主分支，你再重装一下 mv data 和 rescours

**Comment by Mr233sir** [comment]
更新完成后一启动就这样报错
09-19 18:07:51 [SUCCESS] nonebot | NoneBot is initializing...
09-19 18:07:51 [INFO] nonebot | Current Env: prod
09-19 18:07:51 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets"
09-19 18:07:52 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
09-19 18:07:52 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
09-19 18:07:52 [ERROR] nonebot | Failed to import "LittlePaimon.manager.bot_manager"
Traceback (most recent call last):
  File "d:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "d:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "d:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\__init__.py", line 42, in <module>
    load_plugin('LittlePaimon.manager.bot_manager')
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "d:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\manager\bot_manager\__init__.py", line 16, in <module>
    from .handler import check_update, update
  File ".\LittlePaimon\manager\bot_manager\handler.py", line 2, in <module>
    import git
ModuleNotFoundError: No module named 'git'
09-19 18:07:53 [SUCCESS] nonebot | Succeeded to import "LittlePaimon.manager.plugin_manager"
09-19 18:07:53 [SUCCESS] nonebot | Succeeded to import "LittlePaimon.manager.database_manager"
09-19 18:07:53 [SUCCESS] nonebot | Succeeded to import "LittlePaimon.manager.alias_manager"
09-19 18:07:54 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
09-19 18:07:54 [SUCCESS] nonebot | Succeeded to import "Paimon_DailyNote"
09-19 18:07:54 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
09-19 18:07:54 [SUCCESS] nonebot | Succeeded to import "Paimon_MonthInfo"
09-19 18:07:55 [ERROR] nonebot | Failed to import "Paimon_Wiki"
Traceback (most recent call last):
  File "d:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "d:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "d:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "d:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\plugins\Paimon_Wiki\__init__.py", line 18, in <module>
    from .draw_map import init_map, draw_map, get_full_map
  File ".\LittlePaimon\plugins\Paimon_Wiki\draw_map.py", line 9, in <module>
    from .genshinmap import utils, models, request, img, XYPoint
  File ".\LittlePaimon\plugins\Paimon_Wiki\genshinmap\img.py", line 6, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
09-19 18:07:55 [SUCCESS] nonebot | Succeeded to import "news60s"
09-19 18:07:55 [SUCCESS] nonebot | Succeeded to import "Genshin_Voice"
09-19 18:07:55 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
09-19 18:07:55 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
09-19 18:07:56 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
09-19 18:07:56 [SUCCESS] nonebot | Succeeded to import "Genshin_Calendar"
09-19 18:07:56 [SUCCESS] nonebot | Succeeded to import "Paimon_Bind"
09-19 18:07:56 [SUCCESS] nonebot | Succeeded to import "Paimon_Autobbs"
09-19 18:07:57 [SUCCESS] nonebot | Succeeded to import "NoticeAndRequest"
09-19 18:07:57 [SUCCESS] nonebot | Succeeded to import "Genshin_AIVoice"
09-19 18:07:57 [ERROR] nonebot | Failed to import "Learning_Chat"
Traceback (most recent call last):
  File ".\LittlePaimon\plugins\Learning_Chat\models.py", line 8, in <module>
    import jieba_fast.analyse as jieba_analyse
ModuleNotFoundError: No module named 'jieba_fast'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "d:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "d:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "d:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator.XSOOY-20170417C\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-qVEGxkHd-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\plugins\Learning_Chat\__init__.py", line 18, in <module>
    from .models import LearningChat
  File ".\LittlePaimon\plugins\Learning_Chat\models.py", line 10, in <module>
    import jieba.analyse as jieba_analyse
ModuleNotFoundError: No module named 'jieba'
09-19 18:07:57 [SUCCESS] nonebot | Succeeded to import "LittlePaimon"
09-19 18:07:57 [SUCCESS] nonebot | Running NoneBot...

**Comment by CMHopeSunshine** [comment]
缺依赖，装

**Comment by Mr233sir** [comment]
是缺哪些依赖，我试了pip install jieba和jieba_fast和sklearn和git（看上面的错误信息我觉得可能是这些）前3个正常装上去了第4个显示找不到这个，但是错误还在，是要怎么操作吗

**Comment by Mr233sir** [comment]
不好意思我应该用poetry run pip install的，但是还有一个叫git的依赖装不了，显示
PS D:\bot\LittlePaimon> poetry run pip install git
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement git (from versions: none)
ERROR: No matching distribution found for git
但是我这网络没问题也没有开代理，python -V显示的版本是3.8.6

**Comment by forchannot** [comment]
> 不好意思我应该用poetry run pip install的，但是还有一个叫git的依赖装不了，显示 PS D:\bot\LittlePaimon> poetry run pip install git Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple ERROR: Could not find a version that satisfies the requirement git (from versions: none) ERROR: No matching distribution found for git 但是我这网络没问题也没有开代理，python -V显示的版本是3.8.6

git这个依赖全名没记错的话是叫gitpython，你直接poetry install直接一步装完依赖不就好了，依赖都给你放在pyproject.toml了

**Comment by Mr233sir** [comment]
谢了，终于能正常运行了
