### ISSUE TITLE
启动时遇到问题：BaseModel.__init__ pydantic.error_wrappers.ValidationError: 4 validation errors for Config

### ISSUE THREAD

**Issue by YvetteVv** [CMHopeSunshine/LittlePaimon#264]
```
ighthouse@VM-4-2-ubuntu:~/bot/Nonebot2$ nb run
09-21 08:29:54 [SUCCESS] nonebot | NoneBot is initializing...
09-21 08:29:54 [INFO] nonebot | Current Env: prod
Traceback (most recent call last):
  File "/home/lighthouse/.local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lighthouse/bot/Nonebot2/./bot.py", line 21, in <module>
    driver.register_adapter(MIRAI2Adapter)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/driver/driver.py", line 63, in register_adapter
    self._adapters[name] = adapter(self, **kwargs)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/nonebot/adapters/mirai2/adapter.py", line 34, in __init__
    self.mirai_config: Config = Config(**self.config.dict())
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for Config
mirai_verify_key
  field required (type=value_error.missing)
mirai_host
  field required (type=value_error.missing)
mirai_port
  field required (type=value_error.missing)
mirai_qq
  field required (type=value_error.missing)
```

**Comment by CMHopeSunshine** [comment]
你确定这是本项目的报错？报错意思是mirai适配器缺少配置，但是本项目用的是onebot适配器。

**Comment by YvetteVv** [comment]
resolved
