### ISSUE TITLE
dailynote error

### ISSUE THREAD

**Issue by Mohammed0821** [CMHopeSunshine/LittlePaimon#268]
09-21 23:15:44 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.plugins.Paimon_DailyNote, type=message, prio
rity=9, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\Scripts\nb.exe\__mai
n__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\nb
_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\nb
_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\uv
icorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\uv
icorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_unti
l_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_f
orever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_fore
ver
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_on
ce
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File ".\LittlePaimon\plugins\Paimon_DailyNote\__init__.py", line 49, in _
    await ssbq.finish(result, at_sender=True)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\matcher.py", line 468, in finish
    await cls.send(message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\matcher.py", line 453, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\adapters\onebot\v11\bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\adapter\bot.py", line 117, in call_api
    raise exception
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\adapters\onebot\v11\adapter.py", line 132, in _call_api
    return handle_api_result(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='3', msg='SEND_MSG_API_ERROR', retcode
=100, status='failed', wording='请参考 go-cqhttp 端输出'>

py的问题？3.8.6
bot分支 最新code

**Comment by CMHopeSunshine** [comment]
go-cqhttp日志怎么说,，我感觉是风控

**Comment by Mohammed0821** [comment]
群消息发送失败: 账号可能被风控.
但是其他消息都发的出去，目前ssbq和ys是发不出来的，help可用

**Comment by Mohammed0821** [comment]
09-21 23:29:51 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.plugins.Paimon_Info, type=message, priority=
10, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\Scripts\nb.exe\__mai
n__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\cl
ick\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\nb
_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\nb
_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\uv
icorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\uv
icorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_unti
l_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_f
orever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_fore
ver
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_on
ce
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File ".\LittlePaimon\plugins\Paimon_Info\__init__.py", line 116, in _
    await ys.finish(msg, at_sender=True)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\matcher.py", line 468, in finish
    await cls.send(message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\matcher.py", line 453, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\adapters\onebot\v11\bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\adapter\bot.py", line 117, in call_api
    raise exception
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\adapters\onebot\v11\adapter.py", line 132, in _call_api
    return handle_api_result(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-XuYCx89C-py3.8\lib\site-packages\no
nebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='25', msg='SEND_MSG_API_ERROR', retcod
e=100, status='failed', wording='请参考 go-cqhttp 端输出'>

ys的报错
[2022-09-21 23:29:51] [WARNING]: 群消息发送失败: 账号可能被风控.

**Comment by CMHopeSunshine** [comment]
那就是风控，等吧
