### ISSUE TITLE
paimonwiki插件报错

### ISSUE THREAD

**Issue by zfztty** [CMHopeSunshine/LittlePaimon#277]
09-28 19:10:53 [ERROR] nonebot | Failed to import "Paimon_Wiki"
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.
py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.
py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\nb
.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\import
lib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\import
lib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\import
lib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\LittlePaimon\plugins\Paimon_Wiki\__init__.py", line 18, in <module>
    from .draw_map import init_map, draw_map, get_full_map
  File ".\LittlePaimon\plugins\Paimon_Wiki\draw_map.py", line 9, in <module>
    from .genshinmap import utils, models, request, img, XYPoint
  File ".\LittlePaimon\plugins\Paimon_Wiki\genshinmap\img.py", line 6, in <modul
e>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'

想请问一下大佬这是什么原因

**Comment by CMHopeSunshine** [comment]
缺依赖，运行一下`poetry install`

**Comment by zfztty** [comment]
把缺的依赖补上就好了，谢谢大佬，已解决
