### ISSUE TITLE
跟着nonebot安装教程来出现了这个问题

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#28]
super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File ".\LittlePaimon\Guess_voice\__init__.py", line 10, in <module>
    from .handler import Guess, get_random_voice
  File ".\LittlePaimon\Guess_voice\handler.py", line 13, in <module>
    from .download_data import voice_list_by_mys, voice_detail_by_mys
  File ".\LittlePaimon\Guess_voice\download_data.py", line 9, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\nonebot\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File ".\bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\plugin\load.py", line 51, in load_all_plugins
    manager = PluginManager(module_path, plugin_dir)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\plugin\manager.py", line 38, in __init__
    self.list_plugins()
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\plugin\manager.py", line 73, in list_plugins
    raise RuntimeError(
RuntimeError: Plugin already exists: nonebot_plugin_apscheduler! Check your plugin name
请问怎么解决

**Comment by CMHopeSunshine** [comment]
安装一下bs4，`pip install bs4`。
最后那句是说定时任务插件已存在，是不是重复加载了

**Comment by forchannot** [comment]
> 

emmm，好像是的，但是跟着教程来为什么会重复加载呢，改了下能运行了

**Comment by CMHopeSunshine** [comment]
> > 
> 
> emmm，好像是的，但是跟着教程来为什么会重复加载呢，改了下能运行了

应该是`nb plugin install xxx`的方式自动把插件添加到`pyproject.toml`了，换成`pip install xxx`就不会
