### ISSUE TITLE
nb脚手架error

### ISSUE THREAD

**Issue by YvetteVv** [CMHopeSunshine/LittlePaimon#283]
lighthouse@VM-4-2-ubuntu:~/bot/LittlePaimon$ nb
Traceback (most recent call last):
  File "/home/lighthouse/.local/bin/nb", line 5, in <module>
    from nb_cli.__main__ import main
  File "/home/lighthouse/.local/lib/python3.8/site-packages/nb_cli/__init__.py", line 6, in <module>
    from nb_cli.commands.driver import driver
  File "/home/lighthouse/.local/lib/python3.8/site-packages/nb_cli/commands/driver.py", line 4, in <module>
    from nb_cli.handlers import search_driver, install_driver, driver_no_subcommand
  File "/home/lighthouse/.local/lib/python3.8/site-packages/nb_cli/handlers/__init__.py", line 10, in <module>
    from .project import create_project
  File "/home/lighthouse/.local/lib/python3.8/site-packages/nb_cli/handlers/project.py", line 6, in <module>
    from cookiecutter.main import cookiecutter
  File "/home/lighthouse/.local/lib/python3.8/site-packages/cookiecutter/main.py", line 15, in <module>
    from cookiecutter.generate import generate_context, generate_files
  File "/home/lighthouse/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 15, in <module>
    from jinja2 import FileSystemLoader
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/lighthouse/.local/lib/python3.8/site-packages/markupsafe/__init__.py)

**Comment by YvetteVv** [comment]
no need

**Comment by cse0001** [comment]
The root cause with your issue stems from a dependency management conflict between two software ecosystems. According to the error message, your 'markupsafe' was installed using 'pip' at the path `/home/lighthouse/.local/lib/python3.8/site-packages/markupsafe`. The 'jinja2' that depends on it was installed using 'apt' at the path `/usr/lib/python3/dist-packages/jinja2`. The versions of the two are not compatible. In fact, there is a version of 'markupsafe' in the system that 'jinja2' correctly depends on, but the Python interpreter prioritizes the 'markupsafe' installed by 'pip', leading to this issue. There are typically two solutions to this problem: (1) Use 'pip' to uninstall markupsafe, and then reinstall it using 'apt', or uninstall 'jinja2' using 'apt' and reinstall it using 'pip'. (2) Use Python's imp module to customize the path and import the 'markupsafe' from the 'apt' path before importing 'jinja2'. An example is as follows:

    import imp
    path = ['/usr/lib/python3/dist-packages']
    fp, pathname, description = imp.find_module('markupsafe', path)
    imp.load_module("markupsafe", fp, pathname, description)

Hope my diagnosis is helpful to you！ @YvetteVv
