### ISSUE TITLE
无法生成地图

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#285]
10-01 14:47:55 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.plugins.Paimon_Wiki, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nonebot\bot\LittlePaimon\bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\Administrator\Desktop\nonebot\bot\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\__init__.py", line 179, in _
    result = await init_map()
  File "C:\Users\Administrator\Desktop\nonebot\bot\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\draw_map.py", line 40, in init_map
    maps = await request.get_maps(map_id)
  File "C:\Users\Administrator\Desktop\nonebot\bot\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\genshinmap\request.py", line 80, in get_maps
    data = await _request(f"/info?map_id={map_id}&app_sn=ys_obc&lang=zh-cn")
  File "C:\Users\Administrator\Desktop\nonebot\bot\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\genshinmap\request.py", line 32, in _request
    resp.raise_for_status()
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\httpx\_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://api-static.mihoyo.com/common/blackboard/ys_obc/v1/map/info?map_id=2&app_sn=ys_obc&lang=zh-cn'
For more information check: https://httpstatuses.com/404

**Comment by CMHopeSunshine** [comment]
应该是米游社api有改动，观察一下先

**Comment by CMHopeSunshine** [comment]
已修
