### ISSUE TITLE
生成地图时访问的地址报404，手动访问失败

### ISSUE THREAD

**Issue by yaojia25** [CMHopeSunshine/LittlePaimon#297]
大佬你好，我使用生成地图命令时会报错，看日志好像是地图网址404了。日志信息如下
```shell
10-12 23:34:22 [SUCCESS] nonebot | ONEBOT V11 *** | [message.private.friend]: Message 1678165199 from *** "#生成地图"
10-12 23:34:22 [INFO] nonebot | Event will be handled by <Matcher from LittlePaimon.plugins.Paimon_Wiki, type=message, priority=1, temp=False>
10-12 23:34:22 [INFO] nonebot | Matcher <Matcher from LittlePaimon.plugins.Paimon_Wiki, type=message, priority=1, temp=False> running complete
10-12 23:34:22 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.plugins.Paimon_Wiki, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/apps/LittlePaimon/.venv/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "./LittlePaimon/plugins/Paimon_Wiki/__init__.py", line 179, in _
    result = await init_map()
  File "./LittlePaimon/plugins/Paimon_Wiki/draw_map.py", line 40, in init_map
    maps = await request.get_maps(map_id)
  File "./LittlePaimon/plugins/Paimon_Wiki/genshinmap/request.py", line 80, in get_maps
    data = await _request(f"/info?map_id={map_id}&app_sn=ys_obc&lang=zh-cn")
  File "./LittlePaimon/plugins/Paimon_Wiki/genshinmap/request.py", line 32, in _request
    resp.raise_for_status()
  File "/apps/LittlePaimon/.venv/lib/python3.9/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://api-static.mihoyo.com/common/blackboard/ys_obc/v1/map/info?map_id=2&app_sn=ys_obc&lang=zh-cn'
For more information check: https://httpstatuses.com/404
```

**Comment by CMHopeSunshine** [comment]
更新至最新代码了吗，之前修过这个问题了

**Comment by yaojia25** [comment]
> 更新至最新代码了吗，之前修过这个问题了

一直有git pull，但是不知道为啥还是会报错，刚才手动替换了request.py文件就恢复了，可以正常生成了
