### ISSUE TITLE
启动时报错连接数据库失败

### ISSUE THREAD

**Issue by zfztty** [CMHopeSunshine/LittlePaimon#305]
10-17 12:00:35 [WARNING] LittlePaimon | [数据库]连接失败:{e}
10-17 12:00:35 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\connection.py", line 113, in get
    return storage[conn_alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\connection.py", line 76, in _get_
db_info
    return self.db_config[conn_alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\starlette\routing.py", line 635, in lifesp
an
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\starlette\routing.py", line 530, in __aent
er__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\starlette\routing.py", line 612, in startu
p
    await handler()
  File ".\LittlePaimon\__init__.py", line 35, in startup
    await database.connect()
  File ".\LittlePaimon\database\__init__.py", line 64, in connect
    raise e
  File ".\LittlePaimon\database\__init__.py", line 59, in connect
    await Tortoise.init(DATABASE)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\__init__.py", line 574, in init
    cls._init_apps(apps_config)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\__init__.py", line 417, in _init_
apps
    cls._build_initial_querysets()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\__init__.py", line 440, in _build
_initial_querysets
    model._meta.finalise_model()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\models.py", line 308, in finalise
_model
    self._generate_filters()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\models.py", line 476, in _generat
e_filters
    get_overridden_filter_func = self.db.executor_class.get_overridden_filter_fu
nc
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\models.py", line 288, in db
    return connections.get(self.default_connection)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\connection.py", line 115, in get
    connection: BaseDBAsyncClient = self._create_connection(conn_alias)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\connection.py", line 90, in _crea
te_connection
    db_info = self._get_db_info(conn_alias)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\tortoise\connection.py", line 78, in _get_
db_info
    raise ConfigurationError(
tortoise.exceptions.ConfigurationError: Unable to get db settings for alias 'def
ault'. Please check if the config dict contains this alias and try again

10-17 12:00:35 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by zfztty** [comment]
大佬帮忙看看这是什么原因，之前一直用的没问题

**Comment by CMHopeSunshine** [comment]
是不是装了其他插件，比如`haruka`，数据库会冲突不能用

**Comment by zfztty** [comment]
> 是不是装了其他插件，比如`haruka`，数据库会冲突不能用

是装了一下nonebot store的ai画图插件，之后就报错了，有解决办法吗？大佬

**Comment by CMHopeSunshine** [comment]
那暂时只能卸载插件（

**Comment by zfztty** [comment]
> 那暂时只能卸载插件（
好的，谢谢佬

**Comment by Mr233sir** [comment]
> 那暂时只能卸载插件（

大佬可否解决一下，群友都想要这个功能，当然如果解决不了或者不想解决就算了
