### ISSUE TITLE
下载资源的时候一直报错怎么办

### ISSUE THREAD

**Issue by liyoushow** [CMHopeSunshine/LittlePaimon#308]
Traceback (most recent call last):
  File "D:\桌面\LittlePaimon\.\LittlePaimon\utils\tool.py", line 62, in check_resource
    await aiorequests.download(url=f'http://img.genshin.cherishmoon.fun/resources/{resource["path"]}', save_path=file_path)
  File "D:\桌面\LittlePaimon\.\LittlePaimon\utils\requests.py", line 140, in download
    async for chunk in tqdm.asyncio.tqdm(iterable=datas.aiter_bytes(1),
  File "C:\Users\28111\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-ePePlytF-py3.10\lib\site-packages\tqdm\asyncio.py", line 42, in __anext__
    res = await self.iterable_next()
  File "C:\Users\28111\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-ePePlytF-py3.10\lib\site-packages\httpx\_models.py", line 914, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "C:\Users\28111\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-ePePlytF-py3.10\lib\site-packages\httpx\_models.py", line 972, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "C:\Users\28111\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-ePePlytF-py3.10\lib\site-packages\httpx\_client.py", line 146, in __aiter__
    async for chunk in self._stream:
  File "C:\Users\28111\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-ePePlytF-py3.10\lib\site-packages\httpx\_transports\default.py", line 238, in __aiter__
    with map_httpcore_exceptions():
  File "C:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\28111\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-ePePlytF-py3.10\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\28111\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-ePePlytF-py3.10\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\28111\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-ePePlytF-py3.10\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\28111\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-ePePlytF-py3.10\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "D:\桌面\LittlePaimon\.\LittlePaimon\__init__.py", line 38, in startup
    await check_resource()
  File "D:\桌面\LittlePaimon\.\LittlePaimon\utils\tool.py", line 65, in check_resource
    logger.warning('资源检查', f'下载<m>{resource.split("/")[-1]}</m>时<r>出错: {e}</r>')
AttributeError: 'dict' object has no attribute 'split'

**Comment by CMHopeSunshine** [comment]
检查您的网络是否能正常访问`http://img.genshin.cherishmoon.fun/resources/resources_list`，如果开了代理等情况导致不能访问，请先关掉代理
