### ISSUE TITLE
启动时提醒 Application startup failed. Exiting.

### ISSUE THREAD

**Issue by zfztty** [CMHopeSunshine/LittlePaimon#314]
10-26 09:18:04 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\starlette\routing.py", line 635, in lifesp
an
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\starlette\routing.py", line 530, in __aent
er__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\starlette\routing.py", line 612, in startu
p
    await handler()
  File ".\LittlePaimon\__init__.py", line 36, in startup
    from LittlePaimon import web
  File ".\LittlePaimon\web\__init__.py", line 6, in <module>
    from .api import BaseApiRouter
  File ".\LittlePaimon\web\api\__init__.py", line 5, in <module>
    from .status import route as status_route
  File ".\LittlePaimon\web\api\status.py", line 6, in <module>
    from LittlePaimon.utils.status import get_status
  File ".\LittlePaimon\utils\status.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

10-26 09:18:04 [ERROR] uvicorn | Application startup failed. Exiting.
错误提示这个，大佬这个怎么解决

**Comment by CMHopeSunshine** [comment]
`poetry install`安装依赖

**Comment by zfztty** [comment]
> `poetry install`安装依赖

(littlepaimon-py3.8) C:\Users\Administrator\Desktop\pmbot\LittlePaimon>poetry in
stall
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: LittlePaimon (3.0.0beta7)

(littlepaimon-py3.8) C:\Users\Administrator\Desktop\pmbot\LittlePaimon>提示是无

**Comment by CMHopeSunshine** [comment]
`poetry run pip install -r requirements.txt`

**Comment by zfztty** [comment]
> `poetry run pip install -r requirements.txt`

10-26 10:41:49 [SUCCESS] LittlePaimon | [数据库]连接成功
10-26 10:41:50 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\starlette\routing.py", line 635, in lifesp
an
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\starlette\routing.py", line 530, in __aent
er__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-ZLy5lA-a-py3.8\lib\site-packages\starlette\routing.py", line 612, in startu
p
    await handler()
  File ".\LittlePaimon\__init__.py", line 36, in startup
    from LittlePaimon import web
  File ".\LittlePaimon\web\__init__.py", line 6, in <module>
    from .api import BaseApiRouter
  File ".\LittlePaimon\web\api\__init__.py", line 5, in <module>
    from .status import route as status_route
  File ".\LittlePaimon\web\api\status.py", line 6, in <module>
    from LittlePaimon.utils.status import get_status
  File ".\LittlePaimon\utils\status.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

10-26 10:41:50 [ERROR] uvicorn | Application startup failed. Exiting.执行过以后nb run依旧是这个报错

**Comment by zfztty** [comment]
我把缺少的psutil包安装了就能启动了，谢谢佬

**Comment by zfztty** [comment]
更新失败，错误信息：Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v origin
  stderr: 'error: Your local changes to the following files would be overwritten by merge:'，请手动进行更新
at bot执行更新的时候遇见这个是需要手动拉取吗？

**Comment by CMHopeSunshine** [comment]
有本地文件修改导致冲突，要到命令行解决冲突拉取

**Comment by zfztty** [comment]
> 有本地文件修改导致冲突，要到命令行解决冲突拉取

(littlepaimon-py3.8) C:\Users\Administrator\Desktop\pmbot\LittlePaimon>git pull
-v
POST git-upload-pack (375 bytes)
From https://github.com/CMHopeSunshine/LittlePaimon
 = [up to date]      Bot        -> origin/Bot
error: Your local changes to the following files would be overwritten by merge:
        poetry.lock
        pyproject.toml
        requirements.txt
Please commit your changes or stash them before you merge.
Aborting是这个冲突了吗

**Comment by zfztty** [comment]
执行封存git stash，git pull origin和拉取远端把问题解决了，谢谢佬
