### ISSUE TITLE
Bot启动失败

### ISSUE THREAD

**Issue by RoundedOrange** [CMHopeSunshine/LittlePaimon#325]
报错：
```
11-14 09:54:32 [ERROR] nonebot | Failed to import "LittlePaimon"
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/PaimonBot/LittlePaimon/./bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/__init__.py", line 4, in <module>
    from LittlePaimon import database, web
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/web/__init__.py", line 8, in <module>
    from .pages import admin_app, login_page, bind_cookie_page, blank_page
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/web/pages/__init__.py", line 3, in <module>
    from .main import admin_app, blank_page
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/web/pages/main.py", line 4, in <module>
    from .home_page import page as home_page
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/web/pages/home_page.py", line 20, in <module>
    select_log = ButtonGroupSelect(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 4 validation errors for ButtonGroupSelect
options -> 0
  value is not a valid list (type=type_error.list)
options -> 0
  value is not a valid list (type=type_error.list)
options -> 1
  value is not a valid list (type=type_error.list)
options -> 1
  value is not a valid list (type=type_error.list)
```
请问是怎么回事呢

**Comment by CMHopeSunshine** [comment]
`poetry run pip install amis-python --upgrade`

**Comment by RoundedOrange** [comment]
> `poetry run pip install amis-python --upgrade`

用了这个命令后再次启动又报错：
```
11-14 12:17:13 [SUCCESS] LittlePaimon | [数据库]连接成功
11-14 12:17:13 [INFO] LittlePaimon | [资源检查]开始检查资源
11-14 12:17:14 [INFO] nonebot_plugin_gocqhttp | [2563313983] Protocol -> connect to server: 220.194.118.230:8080
11-14 12:17:14 [WARNING] nonebot_plugin_gocqhttp | [2563313983] Protocol -> device lock is disable. http api may fail.
11-14 12:17:15 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/anyio/_core/_sockets.py", line 189, in connect_tcp
    gai_res = await getaddrinfo(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/anyio/_core/_sockets.py", line 496, in getaddrinfo
    gai_res = await get_asynclib().getaddrinfo(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 1754, in getaddrinfo
    result = await get_running_loop().getaddrinfo(
  File "uvloop/loop.pyx", line 1528, in getaddrinfo
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/__init__.py", line 21, in startup
    await check_resource()
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/utils/tool.py", line 88, in check_resource
    resource_list = await aiorequests.get('http://img.genshin.cherishmoon.fun/resources/resources_list')
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/utils/requests.py", line 31, in get
    return await client.get(url,
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

11-14 12:17:15 [ERROR] uvicorn | Application startup failed. Exiting.
11-14 12:17:17 [ERROR] nonebot_plugin_gocqhttp | Thread <Thread(daemon-thread-2563313983, started daemon 139674131584768)> raised unknown exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
> File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/process.py", line 148, in _process_worker
    code = self._process_executor()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/process.py", line 132, in _process_executor
    asyncio.run_coroutine_threadsafe(self.logs.add(log_model), loop=self.loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 930, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "uvloop/loop.pyx", line 1288, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 671, in uvloop.loop.Loop._append_ready_handle
  File "uvloop/loop.pyx", line 703, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/__init__.py:35: RuntimeWarning: coroutine 'LogStorage.add' was never awaited
  loop.create_task(LOG_STORAGE.add(message.rstrip("\n")))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
--- Logging error in Loguru Handler #4 ---
Record was: {'elapsed': datetime.timedelta(seconds=30, microseconds=271374), 'exception': (type=<class 'RuntimeError'>, value=RuntimeError('Event loop is closed'), traceback=<traceback object at 0x7f086b850840>), 'extra': {'nonebot_log_level': 'INFO'}, 'file': (name='process.py', path='/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/process.py'), 'function': '_process_worker', 'level': (name='ERROR', no=40, icon='❌'), 'line': 150, 'message': 'Thread <Thread(daemon-thread-2563313983, started daemon 139674131584768)> raised unknown exception:', 'module': 'process', 'name': 'nonebot_plugin_gocqhttp', 'process': (id=1427, name='MainProcess'), 'thread': (id=139674131584768, name='daemon-thread-2563313983'), 'time': datetime(2022, 11, 14, 12, 17, 17, 909848, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'CST'))}
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/process.py", line 148, in _process_worker
    code = self._process_executor()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/process.py", line 132, in _process_executor
    asyncio.run_coroutine_threadsafe(self.logs.add(log_model), loop=self.loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 930, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "uvloop/loop.pyx", line 1288, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 671, in uvloop.loop.Loop._append_ready_handle
  File "uvloop/loop.pyx", line 703, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/loguru/_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/loguru/_simple_sinks.py", line 113, in write
    self._function(message)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/__init__.py", line 35, in log_sink
    loop.create_task(LOG_STORAGE.add(message.rstrip("\n")))
  File "uvloop/loop.pyx", line 1426, in uvloop.loop.Loop.create_task
  File "uvloop/loop.pyx", line 703, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
--- End of logging error ---
11-14 12:17:17 [WARNING] nonebot_plugin_gocqhttp | Process for 2563313983 exited with code None, retrying to restart... (0/-1)
--- Logging error in Loguru Handler #4 ---
Record was: {'elapsed': datetime.timedelta(seconds=30, microseconds=310406), 'exception': None, 'extra': {'nonebot_log_level': 'INFO'}, 'file': (name='process.py', path='/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/process.py'), 'function': '_process_worker', 'level': (name='WARNING', no=30, icon='⚠️'), 'line': 153, 'message': 'Process for 2563313983 exited with code None, retrying to restart... (0/-1)', 'module': 'process', 'name': 'nonebot_plugin_gocqhttp', 'process': (id=1427, name='MainProcess'), 'thread': (id=139674131584768, name='daemon-thread-2563313983'), 'time': datetime(2022, 11, 14, 12, 17, 17, 948880, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'CST'))}
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/loguru/_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/loguru/_simple_sinks.py", line 113, in write
    self._function(message)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/__init__.py", line 35, in log_sink
    loop.create_task(LOG_STORAGE.add(message.rstrip("\n")))
  File "uvloop/loop.pyx", line 1426, in uvloop.loop.Loop.create_task
  File "uvloop/loop.pyx", line 703, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
--- End of logging error ---
11-14 12:17:20 [ERROR] nonebot_plugin_gocqhttp | Thread <Thread(daemon-thread-2563313983, started daemon 139674131584768)> raised unknown exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
> File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/process.py", line 148, in _process_worker
    code = self._process_executor()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot_plugin_gocqhttp/process/process.py", line 132, in _process_executor
    asyncio.run_coroutine_threadsafe(self.logs.add(log_model), loop=self.loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 930, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "uvloop/loop.pyx", line 1288, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 671, in uvloop.loop.Loop._append_ready_handle
  File "uvloop/loop.pyx", line 703, in uvloop.loop.Loop._check_closed
```
请问该怎么做呢

**Comment by RoundedOrange** [comment]
重启之后好了，谢谢。
