### ISSUE TITLE
大佬问下这是错哪里了，装了go-cqhttp插件后运行直接就报错运行停止了。试过poetry run pip install amis-python --upgrade了

### ISSUE THREAD

**Issue by CC091** [CMHopeSunshine/LittlePaimon#331]
PS C:\Users\27203\Desktop\paimengbot\LittlePaimon> nb run
11-18 17:44:49 [SUCCESS] nonebot | NoneBot is initializing...
11-18 17:44:49 [INFO] nonebot | Current Env: prod
11-18 17:44:49 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
11-18 17:44:49 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
11-18 17:44:51 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
11-18 17:44:51 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets"
11-18 17:44:51 [ERROR] nonebot | Failed to import "LittlePaimon"
Traceback (most recent call last):
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\27203\Desktop\paimengbot\LittlePaimon\.\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\27203\Desktop\paimengbot\LittlePaimon\.\LittlePaimon\__init__.py", line 4, in <module>
    from LittlePaimon import database, web
  File "C:\Users\27203\Desktop\paimengbot\LittlePaimon\.\LittlePaimon\database\__init__.py", line 4, in <module>
    from tortoise import Tortoise
ModuleNotFoundError: No module named 'tortoise'
11-18 17:44:51 [SUCCESS] nonebot | Running NoneBot...
11-18 17:44:51 [INFO] uvicorn | Started server process [5548]
11-18 17:44:51 [INFO] uvicorn | Waiting for application startup.
11-18 17:44:51 [INFO] nonebot_plugin_apscheduler | Scheduler Started
11-18 17:44:53 [ERROR] nonebot_plugin_gocqhttp | An error has been caught in function 'startup', process 'MainProcess' (5548), thread 'MainThread' (2508):
Traceback (most recent call last):
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\uvicorn\lifespan\on.py", line 86, in main
    await app(scope, self.receive, self.send)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\exceptions.py", line 69, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\routing.py", line 659, in __call__
    await self.lifespan(scope, receive, send)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
> File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot_plugin_gocqhttp\__init__.py", line 40, in startup
    await download_gocq()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 107, in download_gocq
    url = await get_fastest_mirror(client)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 91, in get_fastest_mirror
    assert lowest_latency and fastest_url, "No download domain available."
AssertionError: No download domain available.
11-18 17:44:53 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot_plugin_gocqhttp\__init__.py", line 40, in startup
    await download_gocq()
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\loguru\_logger.py", line 1212, in catch_wrapper
    return await function(*args, **kwargs)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 107, in download_gocq
    url = await get_fastest_mirror(client)
  File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 91, in get_fastest_mirror
    assert lowest_latency and fastest_url, "No download domain available."
AssertionError: No download domain available.

11-18 17:44:53 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by CMHopeSunshine** [comment]
2个报错，第一个执行`poetry install`解决，第二个是网络问题，请尝试开代理

**Comment by CC091** [comment]
> 第二个是网络问题，请尝试开代理`poetry install`

第一个怎么执行解决

**Comment by CMHopeSunshine** [comment]
不是说了吗，执行`poetry install`

**Comment by CC091** [comment]
> 不是说了吗，执行`poetry install`

抱歉，刚才显示在第二个后面了

**Comment by CC091** [comment]
Package operations: 20 installs, 0 updates, 0 removals

  • Installing scipy (1.9.3): Failed

  CalledProcessError

  Command 'C:\Users\27203\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-Jh0t5MGg-py3.10\Scripts\python.exe -m pip install --use-pep517 --disable-pip-version-check --prefix C:\Users\27203\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-Jh0t5MGg-py3.10 --no-deps C:\Users\27203\AppData\Local\pypoetry\Cache\artifacts\89\ad\99\e5346206602045b6397e37024bf540f4cd000c0523cc094424b7703677\scipy-1.9.3.tar.gz' returned non-zero exit status 1.

  at ~\AppData\Local\Programs\Python\Python310-32\lib\subprocess.py:526 in run
       522│             # We don't call process.wait() as .__exit__ does that for us.
       523│             raise
       524│         retcode = process.poll()
       525│         if check and retcode:
    →  526│             raise CalledProcessError(retcode, process.args,
       527│                                      output=stdout, stderr=stderr)
       528│     return CompletedProcess(process.args, retcode, stdout, stderr)
       529│
       530│

The following error occurred when trying to handle this error:


  EnvCommandError

  Command C:\Users\27203\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-Jh0t5MGg-py3.10\Scripts\python.exe -m pip install --use-pep517 --disable-pip-version-check --prefix C:\Users\27203\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-Jh0t5MGg-py3.10 --no-deps C:\Users\27203\AppData\Local\pypoetry\Cache\artifacts\89\ad\99\e5346206602045b6397e37024bf540f4cd000c0523cc094424b7703677\scipy-1.9.3.tar.gz errored with the following return code 1, and output:
  Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
  Processing c:\users\27203\appdata\local\pypoetry\cache\artifacts\89\ad\99\e5346206602045b6397e37024bf540f4cd000c0523cc094424b7703677\scipy-1.9.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    Getting requirements to build wheel did not run successfully.
    exit code: 1

    [65 lines of output]
    The Meson build system
    Version: 0.64.0
    Source dir: C:\Users\27203\AppData\Local\Temp\pip-req-build-lajenk6l
    Build dir: C:\Users\27203\AppData\Local\Temp\pip-req-build-lajenk6l\.mesonpy-ojsfxsyt\build
    Build type: native build
    Project name: SciPy
    Project version: 1.9.3
    Activating VS 17.4.1
    C compiler for the host machine: cl (msvc 19.34.31933 "ÓÃÓÚ x64 µÄ Microsoft (R) C/C++ ÓÅ»¯±àÒëÆ÷ 19.34.31933 °æ")
    C linker for the host machine: link link 14.34.31933.0
    C++ compiler for the host machine: cl (msvc 19.34.31933 "ÓÃÓÚ x64 µÄ Microsoft (R) C/C++ ÓÅ»¯±àÒëÆ÷ 19.34.31933 °æ")
    C++ linker for the host machine: link link 14.34.31933.0
    Host machine cpu family: x86_64
    Host machine cpu: x86_64
    Compiler for C supports arguments -Wno-unused-but-set-variable: NO
    Compiler for C supports arguments -Wno-unused-but-set-variable: NO (cached)
    Compiler for C supports arguments -Wno-unused-function: NO
    Compiler for C supports arguments -Wno-conversion: NO
    Compiler for C supports arguments -Wno-misleading-indentation: NO
    Compiler for C supports arguments -Wno-incompatible-pointer-types: NO
    Library m found: NO

    ..\..\meson.build:57:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
    The following exception(s) were encountered:
    Running `ifort --version` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"
    Running `ifort -V` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"
    Running `gfortran --version` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"
    Running `gfortran -V` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"
    Running `flang --version` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"
    Running `flang -V` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"
    Running `pgfortran --version` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"
    Running `pgfortran -V` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"
    Running `g95 --version` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"
    Running `g95 -V` gave "[WinError 2] ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£"

    A full log can be found at C:\Users\27203\AppData\Local\Temp\pip-req-build-lajenk6l\.mesonpy-ojsfxsyt\build\meson-logs\meson-log.txt
    + meson setup --native-file=C:\Users\27203\AppData\Local\Temp\pip-req-build-lajenk6l\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=C:\Users\27203\AppData\Local\Programs\Python\Python310-32 C:\Users\27203\AppData\Local\Temp\pip-req-build-lajenk6l C:\Users\27203\AppData\Local\Temp\pip-req-build-lajenk6l\.mesonpy-ojsfxsyt\build
    Traceback (most recent call last):
      File "C:\Users\27203\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-Jh0t5MGg-py3.10\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
        main()
      File "C:\Users\27203\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-Jh0t5MGg-py3.10\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\27203\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-Jh0t5MGg-py3.10\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
      File "C:\Users\27203\AppData\Local\Temp\pip-build-env-warz8q7y\overlay\Lib\site-packages\mesonpy\__init__.py", line 969, in get_requires_for_build_wheel
        with _project(config_settings) as project:
      File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\contextlib.py", line 135, in __enter__
        return next(self.gen)
      File "C:\Users\27203\AppData\Local\Temp\pip-build-env-warz8q7y\overlay\Lib\site-packages\mesonpy\__init__.py", line 948, in _project
        with Project.with_temp_working_dir(
      File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\contextlib.py", line 135, in __enter__
        return next(self.gen)
      File "C:\Users\27203\AppData\Local\Temp\pip-build-env-warz8q7y\overlay\Lib\site-packages\mesonpy\__init__.py", line 777, in with_temp_working_dir
        yield cls(source_dir, tmpdir, build_dir)
      File "C:\Users\27203\AppData\Local\Temp\pip-build-env-warz8q7y\overlay\Lib\site-packages\mesonpy\__init__.py", line 682, in __init__
        self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
      File "C:\Users\27203\AppData\Local\Temp\pip-build-env-warz8q7y\overlay\Lib\site-packages\mesonpy\__init__.py", line 713, in _configure
        self._meson(
      File "C:\Users\27203\AppData\Local\Temp\pip-build-env-warz8q7y\overlay\Lib\site-packages\mesonpy\__init__.py", line 696, in _meson
        return self._proc('meson', *args)
      File "C:\Users\27203\AppData\Local\Temp\pip-build-env-warz8q7y\overlay\Lib\site-packages\mesonpy\__init__.py", line 691, in _proc
        subprocess.check_call(list(args))
      File "C:\Users\27203\AppData\Local\Programs\Python\Python310-32\lib\subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=C:\\Users\\27203\\AppData\\Local\\Temp\\pip-req-build-lajenk6l\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=C:\\Users\\27203\\AppData\\Local\\Programs\\Python\\Python310-32', 'C:\\Users\\27203\\AppData\\Local\\Temp\\pip-req-build-lajenk6l', 'C:\\Users\\27203\\AppData\\Local\\Temp\\pip-req-build-lajenk6l\\.mesonpy-ojsfxsyt\\build']' returned non-zero exit status 1.
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.


  at ~\AppData\Local\Programs\Python\Python310-32\lib\site-packages\poetry\utils\env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│
      1478│         return decode(output)
      1479│
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install C:/Users/27203/AppData/Local/pypoetry/Cache/artifacts/89/ad/99/e5346206602045b6397e37024bf540f4cd000c0523cc094424b7703677/scipy-1.9.3.tar.gz

  at ~\AppData\Local\Programs\Python\Python310-32\lib\site-packages\poetry\utils\pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│
poetry 
我poetry install好像一直出错，现在可以登上qq了，还是不能import那些

**Comment by CMHopeSunshine** [comment]
好像是你的python缺少一些C模块，试试`poetry run pip install -r requirements.txt`，还是装不上依赖的话，建议退python版本到3.8或者3.9
