### ISSUE TITLE
生成地图报错

### ISSUE THREAD

**Issue by soulrewrite** [CMHopeSunshine/LittlePaimon#332]
查了之前的也没有404，还是同个问题么
已经是最新版
已重启完成，当前版本为3.0.0rc3
```
11-19 18:37:36 [INFO] nonebot | Matcher(type='message', module=LittlePaimon.plugins.Paimon_Wiki) running complete
11-19 18:37:36 [ERROR] nonebot | Running Matcher(type='message', module=LittlePaimon.plugins.Paimon_Wiki) failed.
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "/usr/local/lib/python3.9/ssl.py", line 888, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2633)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 33, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/anyio/streams/tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1258, in receive
    await checkpoint()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 515, in checkpoint
    await sleep(0)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 645, in sleep
    await __sleep0()
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 634, in __sleep0
    yield
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 35, in read
    return b""
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 239, in __aiter__
    async for part in self._httpcore_stream:
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 346, in __aiter__
    async for part in self._stream:
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 300, in __aiter__
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 293, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 165, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/_async/http11.py", line 177, in _receive_event
    data = await self._network_stream.read(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 35, in read
    return b""
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/pm/LittlePaimon/LittlePaimon/plugins/Paimon_Wiki/__init__.py", line 168, in _
    result = await init_map()
  File "/root/pm/LittlePaimon/LittlePaimon/plugins/Paimon_Wiki/draw_map.py", line 46, in init_map
    map_img = await utils.make_map(maps.detail)
  File "/root/pm/LittlePaimon/LittlePaimon/plugins/Paimon_Wiki/genshinmap/utils.py", line 44, in make_map
    maps: List[Image.Image] = await gather(
  File "/root/pm/LittlePaimon/LittlePaimon/plugins/Paimon_Wiki/genshinmap/utils.py", line 16, in get_img
    resp = await CLIENT.get(url)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1628, in send
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1622, in send
    await response.aread()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_models.py", line 896, in aread
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_models.py", line 896, in <listcomp>
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_models.py", line 914, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_models.py", line 972, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 146, in __aiter__
    async for chunk in self._stream:
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 240, in __aiter__
    yield part
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-wNXUEI6j-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout
```

**Comment by CMHopeSunshine** [comment]
网络问题
