### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by 1368129224** [CMHopeSunshine/LittlePaimon#337]
miniconda 创建的虚拟环境，python3.11
根据文档，在修改.env.prod配置文件之后，无法启动bot

.env.prod
```
HOST=0.0.0.0
PORT=13579
LOG_LEVEL=DEBUG
SUPERUSERS=["1368129224"]
NICKNAME=["派蒙"]
COMMAND_START=[""]
COMMAND_SEP=[""]
```

```
(paimon) zooter@zooter-nas:~/LittlePaimon$ poetry run python bot.py
12-06 19:24:40 [SUCCESS] nonebot | NoneBot is initializing...
12-06 19:24:40 [INFO] nonebot | Current Env: prod
12-06 19:24:40 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('0.0.0.0'), 'port': 13579, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'1368129224'}, 'nickname': {'派蒙'}, 'command_start': {''}, 'command_sep': {''}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'prod'}
Traceback (most recent call last):
  File "/home/zooter/LittlePaimon/bot.py", line 18, in <module>
    nonebot.init()
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/nonebot/__init__.py", line 256, in init
    DriverClass = _resolve_combine_expr(config.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/nonebot/__init__.py", line 197, in _resolve_combine_expr
    DriverClass = _resolve_dot_notation(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/nonebot/__init__.py", line 186, in _resolve_dot_notation
    module = importlib.import_module(modulename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 20, in <module>
    from fastapi.responses import Response
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/fastapi/routing.py", line 23, in <module>
    from fastapi.dependencies.models import Dependant
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/fastapi/dependencies/models.py", line 3, in <module>
    from fastapi.security.base import SecurityBase
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/fastapi/security/__init__.py", line 1, in <module>
    from .api_key import APIKeyCookie as APIKeyCookie
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/fastapi/security/api_key.py", line 3, in <module>
    from fastapi.openapi.models import APIKey, APIKeyIn
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/fastapi/openapi/models.py", line 103, in <module>
    class Schema(BaseModel):
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/pydantic/main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/site-packages/pydantic/utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "/home/zooter/miniconda3/envs/paimon/lib/python3.11/inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'not' is not a valid parameter name
```

**Comment by CMHopeSunshine** [comment]
nonebot2所依赖的pydantic尚未完全支持python3.11，建议回退3.9或者3.10版本，相关讨论https://github.com/nonebot/discussions/discussions/229

**Comment by 1368129224** [comment]
使用python3.10，正常启动，感谢！
