### ISSUE TITLE
更新后启动报错

### ISSUE THREAD

**Issue by naotoseri** [CMHopeSunshine/LittlePaimon#339]
12-07 11:24:25 [SUCCESS] nonebot | NoneBot is initializing...
12-07 11:24:25 [INFO] nonebot | Current Env: prod
12-07 11:24:26 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets"
12-07 11:24:26 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
12-07 11:24:26 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
12-07 11:24:27 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
12-07 11:24:31 [SUCCESS] nonebot | Succeeded to import "Paimon_Wiki"
12-07 11:24:31 [SUCCESS] nonebot | Succeeded to import "Paimon_Autobbs"
12-07 11:24:31 [SUCCESS] nonebot | Succeeded to import "tools"
12-07 11:24:33 [SUCCESS] nonebot | Succeeded to import "Learning_Chat"
12-07 11:24:33 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
12-07 11:24:34 [SUCCESS] nonebot | Succeeded to import "Paimon_Bind"
12-07 11:24:34 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
12-07 11:24:34 [SUCCESS] nonebot | Succeeded to import "Mihoyo_bbs"
12-07 11:24:34 [SUCCESS] nonebot | Succeeded to import "random_img"
12-07 11:24:34 [SUCCESS] nonebot | Succeeded to import "Paimon_Plugins"
12-07 11:24:34 [SUCCESS] nonebot | Succeeded to import "Genshin_Voice"
12-07 11:24:34 [SUCCESS] nonebot | Succeeded to import "Paimon_MonthInfo"
12-07 11:24:35 [SUCCESS] nonebot | Succeeded to import "Paimon_Abyss"
12-07 11:24:36 [SUCCESS] nonebot | Succeeded to import "Paimon_Chat"
12-07 11:24:37 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
12-07 11:24:37 [SUCCESS] nonebot | Succeeded to import "Genshin_Calendar"
12-07 11:24:37 [SUCCESS] nonebot | Succeeded to import "plugin_manager"
12-07 11:24:37 [SUCCESS] nonebot | Succeeded to import "bot_manager"
12-07 11:24:37 [SUCCESS] nonebot | Succeeded to import "news60s"
12-07 11:24:37 [SUCCESS] nonebot | Succeeded to import "Paimon_DailyNote"
12-07 11:24:38 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
12-07 11:24:38 [SUCCESS] nonebot | Succeeded to import "NoticeAndRequest"
12-07 11:24:38 [SUCCESS] nonebot | Succeeded to import "web"
12-07 11:24:38 [SUCCESS] nonebot | Succeeded to import "utils"
12-07 11:24:38 [SUCCESS] nonebot | Succeeded to import "config"
12-07 11:24:38 [SUCCESS] nonebot | Succeeded to import "database"
12-07 11:24:38 [SUCCESS] nonebot | Running NoneBot...
12-07 11:24:38 [INFO] uvicorn | Started server process [10884]
12-07 11:24:38 [INFO] uvicorn | Waiting for application startup.
12-07 11:24:38 [INFO] nonebot_plugin_apscheduler | Scheduler Started
12-07 11:24:38 [INFO] nonebot_plugin_gocqhttp | [2031752835] 当前版本:v1.0.0-rc3
12-07 11:24:38 [INFO] nonebot_plugin_gocqhttp | [2031752835] 将使用 device.json 内的设备信息运行Bot.
12-07 11:24:38 [INFO] nonebot_plugin_gocqhttp | [2031752835] 开始尝试登录并同步消息...
12-07 11:24:38 [INFO] nonebot_plugin_gocqhttp | [2031752835] 使用协议: iPad
12-07 11:24:39 [INFO] nonebot_plugin_gocqhttp | [2031752835] Protocol -> connect to server: 117.62.243.225:8080
12-07 11:24:39 [WARNING] nonebot_plugin_gocqhttp | [2031752835] Protocol -> device lock is disable. http api may fail.
12-07 11:24:41 [INFO] nonebot_plugin_gocqhttp | [2031752835] 登录成功 欢迎使用: 草草
12-07 11:24:41 [INFO] nonebot_plugin_gocqhttp | [2031752835] 开始加载好友列表...
12-07 11:24:41 [INFO] nonebot_plugin_gocqhttp | [2031752835] 共加载 11 个好友.
12-07 11:24:41 [INFO] nonebot_plugin_gocqhttp | [2031752835] 开始加载群列表...
12-07 11:24:41 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://0.0.0.0:13579/go-cqhttp/
12-07 11:24:41 [INFO] utils | Scheduler Started
12-07 11:24:41 [INFO] utils | [Web UI]启用成功，默认地址为http://127.0.0.1:13579/LittlePaimon/login
12-07 11:24:41 [INFO] LittlePaimon |
██╗     ██╗████████╗████████╗██╗     ███████╗  ██████╗  █████╗ ██╗███╗   ███╗ ██████╗ ███╗   ██╗
██║     ██║╚══██╔══╝╚══██╔══╝██║     ██╔════╝  ██╔══██╗██╔══██╗██║████╗ ████║██╔═══██╗████╗  ██║
██║     ██║   ██║      ██║   ██║     █████╗    ██████╔╝███████║██║██╔████╔██║██║   ██║██╔██╗ ██║
██║     ██║   ██║      ██║   ██║     ██╔══╝    ██╔═══╝ ██╔══██║██║██║╚██╔╝██║██║   ██║██║╚██╗██║
███████╗██║   ██║      ██║   ███████╗███████╗  ██║     ██║  ██║██║██║ ╚═╝ ██║╚██████╔╝██║ ╚████║
╚══════╝╚═╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝  ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
12-07 11:24:41 [SUCCESS] database | [数据库]连接成功
12-07 11:24:41 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "F:\paimeng\Barbara_3.0\LittlePaimon\.\LittlePaimon\__init__.py", line 40, in startup
    await PluginManager.init()
  File "F:\paimeng\Barbara_3.0\LittlePaimon\.\LittlePaimon\config\plugin\manage.py", line 79, in init
    matcher_info = MatcherInfo.parse_obj(matcher._default_state)
  File "pydantic\main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MatcherInfo
pm_name
  field required (type=value_error.missing)

12-07 11:24:41 [ERROR] uvicorn | Application startup failed. Exiting.
12-07 11:24:41 [ERROR] nonebot_plugin_gocqhttp | Thread <Thread(daemon-thread-2031752835, started daemon 5804)> raised unknown exception:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\process\process.py", line 152, in _process_worker
    code = self._process_executor()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\process\process.py", line 136, in _process_executor
    asyncio.run_coroutine_threadsafe(self.logs.add(log_model), loop=self.loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 885, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 795, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
--- Logging error in Loguru Handler #4 ---
Record was: {'elapsed': datetime.timedelta(seconds=16, microseconds=547475), 'exception': (type=<class 'RuntimeError'>, value=RuntimeError('Event loop is closed'), traceback=<traceback object at 0x0000023F3B3B24C0>), 'extra': {'nonebot_log_level': 'INFO'}, 'file': (name='process.py', path='C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\littlepaimon-dI94aNfb-py3.10\\lib\\site-packages\\nonebot_plugin_gocqhttp\\process\\process.py'), 'function': '_process_worker', 'level': (name='ERROR', no=40, icon='❌'), 'line': 154, 'message': 'Thread <Thread(daemon-thread-2031752835, started daemon 5804)> raised unknown exception:', 'module': 'process', 'name': 'nonebot_plugin_gocqhttp', 'process': (id=10884, name='MainProcess'), 'thread': (id=5804, name='daemon-thread-2031752835'), 'time': datetime(2022, 12, 7, 11, 24, 41, 782108, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\process\process.py", line 152, in _process_worker
    code = self._process_executor()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\process\process.py", line 136, in _process_executor
    asyncio.run_coroutine_threadsafe(self.logs.add(log_model), loop=self.loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 885, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 795, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\loguru\_simple_sinks.py", line 113, in write
    self._function(message)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\__init__.py", line 35, in log_sink
    loop.create_task(LOG_STORAGE.add(message.rstrip("\n")))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 436, in create_task
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
--- End of logging error ---
C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\loguru\_handler.py:182: RuntimeWarning: coroutine 'LogStorage.add' was never awaited
  self._error_interceptor.print(record)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
12-07 11:24:41 [WARNING] nonebot_plugin_gocqhttp | Process for 2031752835 exited with code None, retrying to restart... (0/-1)
--- Logging error in Loguru Handler #4 ---
Record was: {'elapsed': datetime.timedelta(seconds=16, microseconds=575347), 'exception': None, 'extra': {'nonebot_log_level': 'INFO'}, 'file': (name='process.py', path='C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\littlepaimon-dI94aNfb-py3.10\\lib\\site-packages\\nonebot_plugin_gocqhttp\\process\\process.py'), 'function': '_process_worker', 'level': (name='WARNING', no=30, icon='⚠️'), 'line': 157, 'message': 'Process for 2031752835 exited with code None, retrying to restart... (0/-1)', 'module': 'process', 'name': 'nonebot_plugin_gocqhttp', 'process': (id=10884, name='MainProcess'), 'thread': (id=5804, name='daemon-thread-2031752835'), 'time': datetime(2022, 12, 7, 11, 24, 41, 809980, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\loguru\_simple_sinks.py", line 113, in write
    self._function(message)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-dI94aNfb-py3.10\lib\site-packages\nonebot_plugin_gocqhttp\__init__.py", line 35, in log_sink
    loop.create_task(LOG_STORAGE.add(message.rstrip("\n")))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 436, in create_task
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
--- End of logging error ---

**Comment by CMHopeSunshine** [comment]
是不是自己修改过代码，把某个matcher的state给删掉了

**Comment by naotoseri** [comment]
> 是不是自己修改过代码，把某个matcher的state给删掉了

嗯！找到了，已解决

**Comment by yunqing-my** [comment]
12-07 13:07:11 [SUCCESS] nonebot | NoneBot is initializing...
12-07 13:07:11 [INFO] nonebot | Current Env: prod
12-07 13:07:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
12-07 13:07:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
12-07 13:07:14 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
12-07 13:07:14 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets"
12-07 13:07:15 [ERROR] nonebot | Failed to import "LittlePaimon"
Traceback (most recent call last):
  File "D:\python\Anaconda\envs\littlePaimon\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python\Anaconda\envs\littlePaimon\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\python\Anaconda\envs\littlePaimon\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "D:\python\Anaconda\envs\littlePaimon\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program Files\Genshin\littlePaimon\LittlePaimon\.\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "D:\python\Anaconda\envs\littlePaimon\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program Files\Genshin\littlePaimon\LittlePaimon\.\LittlePaimon\__init__.py", line 5, in <module>
    from LittlePaimon import database, web
  File "D:\Program Files\Genshin\littlePaimon\LittlePaimon\.\LittlePaimon\web\__init__.py", line 8, in <module>
    from .pages import admin_app, login_page, bind_cookie_page, blank_page
  File "D:\Program Files\Genshin\littlePaimon\LittlePaimon\.\LittlePaimon\web\pages\__init__.py", line 3, in <module>
    from .main import admin_app, blank_page
  File "D:\Program Files\Genshin\littlePaimon\LittlePaimon\.\LittlePaimon\web\pages\main.py", line 4, in <module>
    from .home_page import page as home_page
  File "D:\Program Files\Genshin\littlePaimon\LittlePaimon\.\LittlePaimon\web\pages\home_page.py", line 50, in <module>
    select_log_level = ButtonGroupSelect(
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 4 validation errors for ButtonGroupSelect
options -> 0
  value is not a valid list (type=type_error.list)
options -> 0
  value is not a valid list (type=type_error.list)
options -> 1
  value is not a valid list (type=type_error.list)
options -> 1
  value is not a valid list (type=type_error.list)
12-07 13:07:15 [SUCCESS] nonebot | Running NoneBot...
12-07 13:07:15 [INFO] uvicorn | Started server process [10340]
12-07 13:07:15 [INFO] uvicorn | Waiting for application startup.
12-07 13:07:15 [INFO] nonebot_plugin_apscheduler | Scheduler Started
12-07 13:07:16 [INFO] nonebot_plugin_gocqhttp | [3458149052] 当前版本:v1.0.0-rc3
12-07 13:07:16 [INFO] nonebot_plugin_gocqhttp | [3458149052] 将使用 device.json 内的设备信息运行Bot.
12-07 13:07:16 [INFO] nonebot_plugin_gocqhttp | [3458149052] 开始尝试登录并同步消息...

您好，可以请问一下您是如何解决的吗。我今天上午一开始也是和您一样的报错，后来从Git上更新了项目文件以后，就变成这样了。

**Comment by CMHopeSunshine** [comment]
> 12-07 13:07:11 [SUCCESS] nonebot | NoneBot is initializing... 12-07 13:07:11 [INFO] nonebot | Current Env: prod 12-07 13:07:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler" 12-07 13:07:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange" 12-07 13:07:14 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp" 12-07 13:07:14 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets" 12-07 13:07:15 [ERROR] nonebot | Failed to import "LittlePaimon" Traceback (most recent call last): File "D:\python\Anaconda\envs\littlePaimon\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\python\Anaconda\envs\littlePaimon\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "D:\python\Anaconda\envs\littlePaimon\Scripts\nb.exe__main__.py", line 7, in sys.exit(main()) File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 1130, in **call** return self.main(*args, **kwargs) File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 1055, in main rv = self.invoke(ctx) File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\click\core.py", line 760, in invoke return __callback(*args, **kwargs) File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nb_cli\commands\main.py", line 30, in run run_bot(file, app) File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot module = importlib.import_module(module_name) File "D:\python\Anaconda\envs\littlePaimon\lib\importlib__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "D:\Program Files\Genshin\littlePaimon\LittlePaimon.\bot.py", line 28, in nonebot.load_plugin("LittlePaimon") File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin return manager.load_plugin(module_path)
> 
> > File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
> > module = importlib.import_module(name)
> > File "D:\python\Anaconda\envs\littlePaimon\lib\importlib__init__.py", line 126, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1050, in _gcd_import
> > File "", line 1027, in _find_and_load
> > File "", line 1006, in _find_and_load_unlocked
> > File "", line 688, in _load_unlocked
> > File "D:\python\Anaconda\envs\littlePaimon\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
> > super().exec_module(module)
> > File "", line 883, in exec_module
> > File "", line 241, in _call_with_frames_removed
> > File "D:\Program Files\Genshin\littlePaimon\LittlePaimon.\LittlePaimon__init__.py", line 5, in 
> > from LittlePaimon import database, web
> > File "D:\Program Files\Genshin\littlePaimon\LittlePaimon.\LittlePaimon\web__init__.py", line 8, in 
> > from .pages import admin_app, login_page, bind_cookie_page, blank_page
> > File "D:\Program Files\Genshin\littlePaimon\LittlePaimon.\LittlePaimon\web\pages__init_.py", line 3, in 
> > from .main import admin_app, blank_page
> > File "D:\Program Files\Genshin\littlePaimon\LittlePaimon.\LittlePaimon\web\pages\main.py", line 4, in 
> > from .home_page import page as home_page
> > File "D:\Program Files\Genshin\littlePaimon\LittlePaimon.\LittlePaimon\web\pages\home_page.py", line 50, in 
> > select_log_level = ButtonGroupSelect(
> > File "pydantic\main.py", line 341, in pydantic.main.BaseModel.**init**
> > raise validation_error
> > pydantic.error_wrappers.ValidationError: 4 validation errors for ButtonGroupSelect
> > options -> 0
> > value is not a valid list (type=type_error.list)
> > options -> 0
> > value is not a valid list (type=type_error.list)
> > options -> 1
> > value is not a valid list (type=type_error.list)
> > options -> 1
> > value is not a valid list (type=type_error.list)
> > 12-07 13:07:15 [SUCCESS] nonebot | Running NoneBot...
> > 12-07 13:07:15 [INFO] uvicorn | Started server process [10340]
> > 12-07 13:07:15 [INFO] uvicorn | Waiting for application startup.
> > 12-07 13:07:15 [INFO] nonebot_plugin_apscheduler | Scheduler Started
> > 12-07 13:07:16 [INFO] nonebot_plugin_gocqhttp | [3458149052] 当前版本:v1.0.0-rc3
> > 12-07 13:07:16 [INFO] nonebot_plugin_gocqhttp | [3458149052] 将使用 device.json 内的设备信息运行Bot.
> > 12-07 13:07:16 [INFO] nonebot_plugin_gocqhttp | [3458149052] 开始尝试登录并同步消息..._
> 
> 您好，可以请问一下您是如何解决的吗。我今天上午一开始也是和您一样的报错，后来从Git上更新了项目文件以后，就变成这样了。

poetry update更新依赖版本
