### ISSUE TITLE
启动报错：[ERROR] uvicorn | Traceback (most recent call last):

### ISSUE THREAD

**Issue by majinnn** [CMHopeSunshine/LittlePaimon#342]
```
12-08 15:26:50 [SUCCESS] nonebot | NoneBot is initializing...
12-08 15:26:50 [INFO] nonebot | Current Env: prod
12-08 15:26:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets"
12-08 15:26:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
12-08 15:26:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
12-08 15:26:52 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
12-08 15:26:55 [SUCCESS] nonebot | Succeeded to import "Paimon_Wiki"
12-08 15:26:55 [SUCCESS] nonebot | Succeeded to import "Mihoyo_bbs"
12-08 15:26:55 [SUCCESS] nonebot | Succeeded to import "Genshin_Voice"
12-08 15:26:55 [SUCCESS] nonebot | Succeeded to import "tools"
12-08 15:26:55 [SUCCESS] nonebot | Succeeded to import "Paimon_Autobbs"
12-08 15:26:56 [SUCCESS] nonebot | Succeeded to import "Paimon_MonthInfo"
12-08 15:26:56 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
12-08 15:26:56 [SUCCESS] nonebot | Succeeded to import "plugin_manager"
12-08 15:26:57 [SUCCESS] nonebot | Succeeded to import "Learning_Chat"
12-08 15:26:58 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
12-08 15:26:58 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
12-08 15:26:58 [SUCCESS] nonebot | Succeeded to import "news60s"
12-08 15:26:59 [SUCCESS] nonebot | Succeeded to import "bot_manager"
12-08 15:26:59 [SUCCESS] nonebot | Succeeded to import "NoticeAndRequest"
12-08 15:26:59 [SUCCESS] nonebot | Succeeded to import "Genshin_Calendar"
12-08 15:26:59 [SUCCESS] nonebot | Succeeded to import "Paimon_Bind"
12-08 15:27:00 [SUCCESS] nonebot | Succeeded to import "Paimon_DailyNote"
12-08 15:27:00 [SUCCESS] nonebot | Succeeded to import "Paimon_Abyss"
12-08 15:27:00 [SUCCESS] nonebot | Succeeded to import "LittlePaimon"
12-08 15:27:00 [SUCCESS] nonebot | Running NoneBot...
12-08 15:27:00 [INFO] uvicorn | Started server process [27736]
12-08 15:27:00 [INFO] uvicorn | Waiting for application startup.
12-08 15:27:00 [INFO] nonebot_plugin_apscheduler | Scheduler Started
12-08 15:27:00 [INFO] LittlePaimon | Scheduler Started
12-08 15:27:00 [INFO] LittlePaimon | [Web UI]启用成功，默认地址为http://127.0.0.1:13579/LittlePaimon/login
12-08 15:27:00 [INFO] LittlePaimon |
██╗     ██╗████████╗████████╗██╗     ███████╗  ██████╗  █████╗ ██╗███╗   ███╗ ██████╗ ███╗   ██╗
██║     ██║╚══██╔══╝╚══██╔══╝██║     ██╔════╝  ██╔══██╗██╔══██╗██║████╗ ████║██╔═══██╗████╗  ██║
██║     ██║   ██║      ██║   ██║     █████╗    ██████╔╝███████║██║██╔████╔██║██║   ██║██╔██╗ ██║
██║     ██║   ██║      ██║   ██║     ██╔══╝    ██╔═══╝ ██╔══██║██║██║╚██╔╝██║██║   ██║██║╚██╗██║
███████╗██║   ██║      ██║   ███████╗███████╗  ██║     ██║  ██║██║██║ ╚═╝ ██║╚██████╔╝██║ ╚████║
╚══════╝╚═╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝  ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
12-08 15:27:00 [SUCCESS] LittlePaimon | [数据库]连接成功
12-08 15:27:00 [SUCCESS] LittlePaimon | [插件管理器]初始化完成
12-08 15:27:00 [INFO] LittlePaimon | [资源检查]开始检查资源
12-08 15:27:00 [INFO] LittlePaimon | [Playwright]正在安装 chromium
12-08 15:27:00 [INFO] LittlePaimon | [Playwright]正在安装依赖
BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
sh: apt-get: command not found
Failed to install browser dependencies
Error: Installation process exited with code: 127
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
12-08 15:27:01 [ERROR] uvicorn | Traceback (most recent call last):
  File "/paimeng/LittlePaimon/./LittlePaimon/utils/brower.py", line 19, in init
    _browser = await launch_browser(**kwargs)
  File "/paimeng/LittlePaimon/./LittlePaimon/utils/brower.py", line 30, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 12664, in launch
    await self._impl_obj.launch(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libatspi.so.0                                    ║
║     libXcomposite.so.1                               ║
║     libXrandr.so.2                                   ║
║     libxkbcommon.so.0                                ║
║     libpango-1.0.so.0                                ║
║     libasound.so.2                                   ║
╚══════════════════════════════════════════════════════╝

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/paimeng/LittlePaimon/./LittlePaimon/utils/brower.py", line 53, in start_browser
    await get_browser(**kwargs)
  File "/paimeng/LittlePaimon/./LittlePaimon/utils/brower.py", line 34, in get_browser
    return _browser or await init(**kwargs)
  File "/paimeng/LittlePaimon/./LittlePaimon/utils/brower.py", line 24, in init
    _browser = await launch_browser(**kwargs)
  File "/paimeng/LittlePaimon/./LittlePaimon/utils/brower.py", line 30, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 12664, in launch
    await self._impl_obj.launch(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-ur9_DIB1-py3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libatspi.so.0                                    ║
║     libXcomposite.so.1                               ║
║     libXrandr.so.2                                   ║
║     libxkbcommon.so.0                                ║
║     libpango-1.0.so.0                                ║
║     libasound.so.2                                   ║
╚══════════════════════════════════════════════════════╝

12-08 15:27:01 [ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by CMHopeSunshine** [comment]
缺库，~~（远离CentOS）~~ 安装库`yum install -y alsa-lib at-spi2-atk at-spi2-core atk cairo cups-libs dbus-libs expat flac-libs gdk-pixbuf2 glib2 glibc gtk3 libX11 libXcomposite libXdamage libXext libXfixes libXrandr libXtst libcanberra-gtk3 libdrm libgcc libstdc++ libxcb libxkbcommon libxshmfence libxslt mesa-libgbm nspr nss nss-util pango policycoreutils policycoreutils-python-utils zlib cairo-gobject centos-indexhtml dbus-glib fontconfig freetype gtk2 libXcursor libXi libXrender libXt liberation-fonts-common liberation-sans-fonts libffi mozilla-filesystem p11-kit-trust pipewire-libs harfbuzz-icu libglvnd-glx libglvnd-egl libnotify opus woff2 gstreamer1-plugins-base gstreamer1-plugins-bad-free openjpeg2 libwebp enchant libsecret hyphen libglvnd-gles`

**Comment by majinnn** [comment]
> 缺库，~（远离CentOS）~ 安装库`yum install -y alsa-lib at-spi2-atk at-spi2-core atk cairo cups-libs dbus-libs expat flac-libs gdk-pixbuf2 glib2 glibc gtk3 libX11 libXcomposite libXdamage libXext libXfixes libXrandr libXtst libcanberra-gtk3 libdrm libgcc libstdc++ libxcb libxkbcommon libxshmfence libxslt mesa-libgbm nspr nss nss-util pango policycoreutils policycoreutils-python-utils zlib cairo-gobject centos-indexhtml dbus-glib fontconfig freetype gtk2 libXcursor libXi libXrender libXt liberation-fonts-common liberation-sans-fonts libffi mozilla-filesystem p11-kit-trust pipewire-libs harfbuzz-icu libglvnd-glx libglvnd-egl libnotify opus woff2 gstreamer1-plugins-base gstreamer1-plugins-bad-free openjpeg2 libwebp enchant libsecret hyphen libglvnd-gles`

谢谢大佬，🌹
