### ISSUE TITLE
重启服务器后，再次启动小派蒙报错

### ISSUE THREAD

**Issue by Orangenwasser** [CMHopeSunshine/LittlePaimon#344]
报错命令行如下：

12-09 13:22:07 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Folivora\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-u9ZF7b63-py3.9\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Folivora\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-u9ZF7b63-py3.9\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Folivora\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-u9ZF7b63-py3.9\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "D:\LittlePaimon\.\LittlePaimon\__init__.py", line 40, in startup
    await check_resource()
  File "D:\LittlePaimon\.\LittlePaimon\utils\tool.py", line 89, in check_resource
    resource_list = resource_list.json()
  File "C:\Users\Folivora\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-u9ZF7b63-py3.9\lib\site-packages\httpx\_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "D:\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

12-09 13:22:07 [ERROR] uvicorn | Application startup failed. Exiting.

最近一段时间只修改过60秒读新闻的API地址

**Comment by CMHopeSunshine** [comment]
请更新至最新版本

**Comment by Orangenwasser** [comment]
> 请更新至最新版本

感谢，我以为是库依赖的问题，原来是这么简单的问题
