### ISSUE TITLE
ysd命令报错

### ISSUE THREAD

**Issue by RoundedOrange** [CMHopeSunshine/LittlePaimon#348]
更新到最新版本后报错了，重启服务器也是没用，报错日志：
```
12-13 21:08:42 [INFO] nonebot | Matcher(type='message', module=LittlePaimon.plugins.Paimon_Info) running complete
12-13 21:08:42 [ERROR] nonebot | Running Matcher(type='message', module=LittlePaimon.plugins.Paimon_Info) failed.
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/littlepaimon-Yl79Fm97-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/plugins/Paimon_Info/__init__.py", line 207, in _
    character_info = await gim.get_character(name=character, data_source='enka')
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/utils/genshin.py", line 176, in get_character
    await self.update_from_enka()
  File "/root/PaimonBot/LittlePaimon/./LittlePaimon/utils/genshin.py", line 67, in update_from_enka
    await PlayerInfo.update_info(self.user_id, self.uid, data['playerInfo'], 'enka')
KeyError: 'playerInfo'
```

**Comment by Cheshire-Nya** [comment]
是enka.network寄了

**Comment by RoundedOrange** [comment]
啊和我上次一样的问题，那现在只能等等了。
