### ISSUE TITLE
最新代码启动报错

### ISSUE THREAD

**Issue by YueLinXieK** [CMHopeSunshine/LittlePaimon#350]
系统：CentOS 7
python版本：3.9.0
报错日志：
12-19 12:24:19 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets"
12-19 12:24:19 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
12-19 12:24:19 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
12-19 12:24:19 [ERROR] nonebot | Failed to import "LittlePaimon"
Traceback (most recent call last):
  File "/home/nb-cli/.local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/python3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./LittlePaimon/__init__.py", line 5, in <module>
    from LittlePaimon import database, web
  File "./LittlePaimon/web/__init__.py", line 7, in <module>
    from .api import BaseApiRouter
  File "./LittlePaimon/web/api/__init__.py", line 3, in <module>
    from .bot_info import route as bot_info_route
  File "./LittlePaimon/web/api/bot_info.py", line 16, in <module>
    from .utils import authentication
  File "./LittlePaimon/web/api/utils.py", line 5, in <module>
    from jose import jwt
  File "/home/nb-cli/.local/lib/python3.9/site-packages/jose.py", line 546
    print decrypt(deserialize_compact(jwt), {'k':key},
          ^
SyntaxError: invalid syntax
12-19 12:24:19 [SUCCESS] nonebot | Running NoneBot...

**Comment by CMHopeSunshine** [comment]
是不是修改过python库下的jose.py，试试poetry run pip uninstall python-jose然后poetry run pip install python-jose

**Comment by YueLinXieK** [comment]
问题解决了，感谢大佬
