### ISSUE TITLE
wiki模块加载失败

### ISSUE THREAD

**Issue by xrzxrzx** [CMHopeSunshine/LittlePaimon#369]
系统是windows11，启动bot初始化时，有wiki模块加载失败的报错，但其他功能都能正常使用
```
\LittlePaimon>poetry run nb run
01-18 03:31:46 [SUCCESS] nonebot | NoneBot is initializing...
01-18 03:31:46 [INFO] nonebot | Current Env: prod
01-18 03:31:47 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
01-18 03:31:47 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
01-18 03:31:49 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
01-18 03:31:51 [SUCCESS] nonebot | Succeeded to import "NoticeAndRequest"
01-18 03:31:51 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
01-18 03:31:51 [SUCCESS] nonebot | Succeeded to import "Mihoyo_bbs"
01-18 03:31:51 [SUCCESS] nonebot | Succeeded to import "Paimon_MonthInfo"
01-18 03:31:52 [SUCCESS] nonebot | Succeeded to import "Learning_Chat"
01-18 03:31:52 [SUCCESS] nonebot | Succeeded to import "Paimon_DailyNote"
01-18 03:31:52 [SUCCESS] nonebot | Succeeded to import "tools"
01-18 03:31:52 [SUCCESS] nonebot | Succeeded to import "Paimon_Abyss"
01-18 03:31:52 [SUCCESS] nonebot | Succeeded to import "plugin_manager"
01-18 03:31:52 [SUCCESS] nonebot | Succeeded to import "Paimon_Bind"
01-18 03:31:52 [SUCCESS] nonebot | Succeeded to import "Genshin_Calendar"
01-18 03:31:53 [ERROR] nonebot | Failed to import "Paimon_Wiki"
Traceback (most recent call last):
  File "E:\作品\QQ机器人\LittlePaimon\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\作品\QQ机器人\LittlePaimon\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\作品\QQ机器人\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\__init__.py", line 24, in <module>
    from .draw_map import init_map, draw_map, get_full_map
  File "E:\作品\QQ机器人\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\draw_map.py", line 11, in <module>
    from .genshinmap import utils, models, request, img, XYPoint
  File "E:\作品\QQ机器人\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\genshinmap\img.py", line 6, in <module>
    from sklearn.cluster import KMeans
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\sklearn\cluster\__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\sklearn\cluster\_spectral.py", line 20, in <module>
    from ..metrics.pairwise import pairwise_kernels, KERNEL_PARAMS
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\sklearn\metrics\__init__.py", line 42, in <module>
    from . import cluster
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\sklearn\metrics\cluster\__init__.py", line 22, in <module>
    from ._unsupervised import silhouette_samples
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\sklearn\metrics\cluster\_unsupervised.py", line 16, in <module>
    from ..pairwise import pairwise_distances_chunked
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\sklearn\metrics\pairwise.py", line 33, in <module>
    from ._pairwise_distances_reduction import ArgKmin
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\sklearn\metrics\_pairwise_distances_reduction\__init__.py", line 89, in <module>
    from ._dispatcher import (
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-7SGtkm6I-py3.10\lib\site-packages\sklearn\metrics\_pairwise_distances_reduction\_dispatcher.py", line 11, in <module>
    from ._base import _sqeuclidean_row_norms32, _sqeuclidean_row_norms64
  File "sklearn\metrics\_pairwise_distances_reduction\_base.pyx", line 1, in init sklearn.metrics._pairwise_distances_reduction._base
ImportError: DLL load failed while importing _datasets_pair: 文件名或扩展名太长。
01-18 03:31:53 [SUCCESS] nonebot | Succeeded to import "Paimon_Autobbs"
01-18 03:31:53 [SUCCESS] nonebot | Succeeded to import "news60s"
01-18 03:31:53 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
01-18 03:31:54 [SUCCESS] nonebot | Succeeded to import "bot_manager"
01-18 03:31:54 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
01-18 03:31:54 [SUCCESS] nonebot | Succeeded to import "Genshin_Voice"
01-18 03:31:54 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
01-18 03:31:54 [SUCCESS] nonebot | Succeeded to import "LittlePaimon"
01-18 03:31:54 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
01-18 03:31:54 [SUCCESS] nonebot | Running NoneBot...
01-18 03:31:54 [INFO] uvicorn | Started server process [14588]
01-18 03:31:54 [INFO] uvicorn | Waiting for application startup.
01-18 03:31:54 [INFO] nonebot_plugin_apscheduler | Scheduler Started
01-18 03:31:55 [INFO] nonebot_plugin_gocqhttp | [2197770490] 当前版本:v1.0.0-rc4
01-18 03:31:55 [INFO] nonebot_plugin_gocqhttp | [2197770490] 将使用 device.json 内的设备信息运行Bot.
01-18 03:31:55 [INFO] nonebot_plugin_gocqhttp | [2197770490] 开始尝试登录并同步消息...
01-18 03:31:55 [INFO] nonebot_plugin_gocqhttp | [2197770490] 使用协议: iPad
01-18 03:31:55 [INFO] nonebot_plugin_gocqhttp | [2197770490] Protocol -> connect to server: 120.232.69.173:8080
01-18 03:31:55 [WARNING] nonebot_plugin_gocqhttp | [2197770490] Protocol -> device lock is disable. http api may fail.
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | [2197770490] 登录成功 欢迎使用: 小派蒙
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | [2197770490] 开始加载好友列表...
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | [2197770490] 共加载 7 个好友.
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | [2197770490] 开始加载群列表...
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | [2197770490] 共加载 7 个群.
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | go-cqhttp for 2197770490 has successfully started.
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | [2197770490] 资源初始化完成, 开始处理信息.
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | [2197770490] アトリは、高性能ですから!
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | [2197770490] 正在检查更新.
01-18 03:31:57 [INFO] nonebot_plugin_gocqhttp | [2197770490] 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:13579/onebot/v11/ws
01-18 03:31:58 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://0.0.0.0:13579/go-cqhttp/
01-18 03:31:58 [INFO] LittlePaimon | Scheduler Started
01-18 03:31:58 [INFO] LittlePaimon | [Web UI]启用成功，默认地址为http://127.0.0.1:13579/LittlePaimon/login
```

**Comment by CMHopeSunshine** [comment]
`ImportError: DLL load failed while importing _datasets_pair: 文件名或扩展名太长。`
从未见过的报错...试试把scikit-learn库卸了重装一下

**Comment by CMHopeSunshine** [comment]
问了下人，可能是中文路径的原因

**Comment by xrzxrzx** [comment]
还是不行，重装了那个库，还换了英文路径，但还是一样的报错
```
E:\LittlePaimon>poetry run nb run
01-18 21:16:17 [SUCCESS] nonebot | NoneBot is initializing...
01-18 21:16:17 [INFO] nonebot | Current Env: prod
01-18 21:16:17 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
01-18 21:16:18 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
01-18 21:16:20 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
01-18 21:16:22 [SUCCESS] nonebot | Succeeded to import "news60s"
01-18 21:16:22 [SUCCESS] nonebot | Succeeded to import "NoticeAndRequest"
01-18 21:16:23 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
01-18 21:16:23 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
01-18 21:16:23 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
01-18 21:16:23 [SUCCESS] nonebot | Succeeded to import "Paimon_Autobbs"
01-18 21:16:24 [SUCCESS] nonebot | Succeeded to import "Learning_Chat"
01-18 21:16:24 [SUCCESS] nonebot | Succeeded to import "Genshin_Voice"
01-18 21:16:24 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
01-18 21:16:25 [SUCCESS] nonebot | Succeeded to import "Paimon_Abyss"
01-18 21:16:25 [SUCCESS] nonebot | Succeeded to import "Paimon_MonthInfo"
01-18 21:16:25 [SUCCESS] nonebot | Succeeded to import "plugin_manager"
01-18 21:16:25 [SUCCESS] nonebot | Succeeded to import "tools"
01-18 21:16:25 [SUCCESS] nonebot | Succeeded to import "Genshin_Calendar"
01-18 21:16:25 [SUCCESS] nonebot | Succeeded to import "bot_manager"
01-18 21:16:25 [SUCCESS] nonebot | Succeeded to import "Paimon_DailyNote"
01-18 21:16:26 [ERROR] nonebot | Failed to import "Paimon_Wiki"
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\LittlePaimon\.\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\LittlePaimon\.\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\LittlePaimon\.\LittlePaimon\plugins\Paimon_Wiki\__init__.py", line 24, in <module>
    from .draw_map import init_map, draw_map, get_full_map
  File "E:\LittlePaimon\.\LittlePaimon\plugins\Paimon_Wiki\draw_map.py", line 11, in <module>
    from .genshinmap import utils, models, request, img, XYPoint
  File "E:\LittlePaimon\.\LittlePaimon\plugins\Paimon_Wiki\genshinmap\img.py", line 6, in <module>
    from sklearn.cluster import KMeans
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\sklearn\cluster\__init__.py", line 6, in <module>
    from ._spectral import spectral_clustering, SpectralClustering
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\sklearn\cluster\_spectral.py", line 20, in <module>
    from ..metrics.pairwise import pairwise_kernels, KERNEL_PARAMS
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\sklearn\metrics\__init__.py", line 42, in <module>
    from . import cluster
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\sklearn\metrics\cluster\__init__.py", line 22, in <module>
    from ._unsupervised import silhouette_samples
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\sklearn\metrics\cluster\_unsupervised.py", line 16, in <module>
    from ..pairwise import pairwise_distances_chunked
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\sklearn\metrics\pairwise.py", line 33, in <module>
    from ._pairwise_distances_reduction import ArgKmin
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\sklearn\metrics\_pairwise_distances_reduction\__init__.py", line 89, in <module>
    from ._dispatcher import (
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages\sklearn\metrics\_pairwise_distances_reduction\_dispatcher.py", line 11, in <module>
    from ._base import _sqeuclidean_row_norms32, _sqeuclidean_row_norms64
  File "sklearn\metrics\_pairwise_distances_reduction\_base.pyx", line 1, in init sklearn.metrics._pairwise_distances_reduction._base
ImportError: DLL load failed while importing _datasets_pair: 文件名或扩展名太长。
01-18 21:16:26 [SUCCESS] nonebot | Succeeded to import "Mihoyo_bbs"
01-18 21:16:27 [SUCCESS] nonebot | Succeeded to import "Paimon_Bind"
01-18 21:16:27 [SUCCESS] nonebot | Succeeded to import "LittlePaimon"
01-18 21:16:27 [SUCCESS] nonebot | Running NoneBot...
01-18 21:16:27 [INFO] uvicorn | Started server process [30292]
01-18 21:16:27 [INFO] uvicorn | Waiting for application startup.
01-18 21:16:27 [INFO] nonebot_plugin_apscheduler | Scheduler Started
01-18 21:16:28 [INFO] nonebot_plugin_gocqhttp | [2197770490] 当前版本:v1.0.0-rc4
01-18 21:16:28 [INFO] nonebot_plugin_gocqhttp | [2197770490] 将使用 device.json 内的设备信息运行Bot.
01-18 21:16:28 [INFO] nonebot_plugin_gocqhttp | [2197770490] 开始尝试登录并同步消息...
01-18 21:16:28 [INFO] nonebot_plugin_gocqhttp | [2197770490] 使用协议: iPad
01-18 21:16:29 [INFO] nonebot_plugin_gocqhttp | [2197770490] Protocol -> connect to server: 120.232.69.213:8080
01-18 21:16:29 [WARNING] nonebot_plugin_gocqhttp | [2197770490] Protocol -> device lock is disable. http api may fail.
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | [2197770490] 登录成功 欢迎使用: 小派蒙
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | [2197770490] 开始加载好友列表...
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | [2197770490] 共加载 8 个好友.
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | [2197770490] 开始加载群列表...
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | [2197770490] 共加载 8 个群.
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | [2197770490] 资源初始化完成, 开始处理信息.
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | go-cqhttp for 2197770490 has successfully started.
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | [2197770490] アトリは、高性能ですから!
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | [2197770490] 正在检查更新.
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | [2197770490] 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:13579/onebot/v11/ws
01-18 21:16:31 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://0.0.0.0:13579/go-cqhttp/
01-18 21:16:31 [INFO] LittlePaimon | Scheduler Started
01-18 21:16:31 [INFO] LittlePaimon | [Web UI]启用成功，默认地址为http://127.0.0.1:13579/LittlePaimon/login
01-18 21:16:31 [INFO] LittlePaimon |
██╗     ██╗████████╗████████╗██╗     ███████╗  ██████╗  █████╗ ██╗███╗   ███╗ ██████╗ ███╗   ██╗
██║     ██║╚══██╔══╝╚══██╔══╝██║     ██╔════╝  ██╔══██╗██╔══██╗██║████╗ ████║██╔═══██╗████╗  ██║
██║     ██║   ██║      ██║   ██║     █████╗    ██████╔╝███████║██║██╔████╔██║██║   ██║██╔██╗ ██║
██║     ██║   ██║      ██║   ██║     ██╔══╝    ██╔═══╝ ██╔══██║██║██║╚██╔╝██║██║   ██║██║╚██╗██║
███████╗██║   ██║      ██║   ███████╗███████╗  ██║     ██║  ██║██║██║ ╚═╝ ██║╚██████╔╝██║ ╚████║
╚══════╝╚═╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝  ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
01-18 21:16:31 [SUCCESS] LittlePaimon | [数据库]连接成功
```

**Comment by CMHopeSunshine** [comment]
应该是你的虚拟环境的名字太长了...
`C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\littlepaimon-WD8tW4uR-py3.10\lib\site-packages`
这也太长了，尝试运行`poetry env remove python`（该命令是删除当前的虚拟环境）然后`poetry config virtualenvs.in_project true`（该命令是将虚拟环境的目录设置在bot当前目录），最后运行`poetry install`重新安装依赖

**Comment by xrzxrzx** [comment]
用这个方法试了两次，虚拟环境都没改成功，然后我把图方便从微软应用商店下的python卸了重装了个官网的解决了，谢了
