### ISSUE TITLE
[bug]ysc指令请求失败【httpx.ConnectError: [Errno 11001] getaddrinfo failed】

### ISSUE THREAD

**Issue by YouYouLip** [CMHopeSunshine/LittlePaimon#385]
02-10 00:13:29 [ERROR] nonebot | Running Matcher(type='message', module=LittlePaimon.plugins.Paimon_Info) failed.
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\anyio\_core\_sockets.py", line 186, in connect_tcp
    addr_obj = ip_address(remote_host)
  File "C:\Program Files\Python310\lib\ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'img.genshin.cherishmoon.fun' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\backends\asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\anyio\_core\_sockets.py", line 189, in connect_tcp
    gai_res = await getaddrinfo(
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\_async\connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\backends\auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\LittlePaimon-Bot\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\LittlePaimon-Bot\LittlePaimon\plugins\Paimon_Info\__init__.py", line 169, in _
    img, temp_img = await draw_chara_card(character_info)
  File "D:\LittlePaimon-Bot\LittlePaimon\plugins\Paimon_Info\draw_character_card.py", line 29, in draw_chara_card
    img = await aiorequests.get_img(f'http://img.genshin.cherishmoon.fun/{info.name}', mode='RGBA', follow_redirects=True)
  File "D:\LittlePaimon-Bot\LittlePaimon\utils\requests.py", line 95, in get_img
    resp = await client.get(url,
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ASUS\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-4hbe8AO3-py3.10\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

**Comment by CMHopeSunshine** [comment]
请更新到最新版本，旧版本api已停止使用

**Comment by YouYouLip** [comment]
> 请更新到最新版本，旧版本api已停止使用

尴尬了 光看见添加定轨没注意到更换api了
