### ISSUE TITLE
抽卡记录功能报错

### ISSUE THREAD

**Issue by WindraiteLesd** [CMHopeSunshine/LittlePaimon#39]
nonebot版本是beta3的，并且刚克隆了一次master分支
Python3.9.7
```
[ERROR] nonebot | Running matcher <Matcher from LittlePaimon.Paimon_Gacha_Log, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\LesdNoneBot2\bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\ProgramData\Anaconda3\envs\lesd2\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\Administrator\Desktop\LesdNoneBot2\LittlePaimon\Paimon_Gacha_Log\__init__.py", line 93, in update_ckjl
    await get_data(url)
  File "C:\Users\Administrator\Desktop\LesdNoneBot2\LittlePaimon\Paimon_Gacha_Log\gacha_logs.py", line 64, in get_data
    gachaLog = await getGachaLogs(url, gachaTypeId)
  File "C:\Users\Administrator\Desktop\LesdNoneBot2\LittlePaimon\Paimon_Gacha_Log\gacha_logs.py", line 22, in getGachaLogs
    gacha = j["data"]["list"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by CMHopeSunshine** [comment]
已修复 [c71ce7f](https://github.com/CMHopeSunshine/LittlePaimon/commit/c71ce7fa5c886389a524a7af0ed2e0b763e5b02b)
