### ISSUE TITLE
[问题]apscheduler插件不能通过nb指令卸载（？）

### ISSUE THREAD

**Issue by YouYouLip** [CMHopeSunshine/LittlePaimon#402]
虽然....我知道apscheduler是绝大部分定时任务依赖的前置，但 为什么不让卸载呢...？ 可以通过nb安装 但是不能通过nb卸载 并且只有apscheduler会这样

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\asus\.local\bin\nb.exe\__main__.py", line 7, in <module>
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\__main__.py", line 7, in main
    anyio.run(cli_main, *args)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_core\_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\__init__.py", line 35, in cli_main
    return await run_sync(cli_sync)(*args, **kwargs)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\cli\utils.py", line 61, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\cli\utils.py", line 69, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\cli\commands\plugin.py", line 187, in uninstall
    GLOBAL_CONFIG.remove_plugin(plugin.module_name)
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\nb_cli\config\parser.py", line 80, in remove_plugin
    plugins.remove(plugin)
  File "C:\Program Files\Python310\lib\_collections_abc.py", line 1163, in remove
    del self[self.index(value)]
  File "C:\Users\ASUS\.local\pipx\venvs\nb-cli\lib\site-packages\tomlkit\items.py", line 1402, in __delitem__
    and "\n" not in self._value[idx].indent.s
AttributeError: 'NoneType' object has no attribute 's'

**Comment by CMHopeSunshine** [comment]
这问题应该去[nb-cli](https://github.com/nonebot/nb-cli)问，我这里看不懂是什么问题

**Comment by YouYouLip** [comment]
> 这问题应该去[nb-cli](https://github.com/nonebot/nb-cli)问，我这里看不懂是什么问题

这样啊 那我去问问去
