### ISSUE TITLE
[问题]Playwright不支持nas的linux

### ISSUE THREAD

**Issue by Ventsze** [CMHopeSunshine/LittlePaimon#405]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.8.12

### 问题描述

nb paimon run 运行报错 卡在正在安装依赖这里

### 问题截图

03-07 15:43:23 [INFO] LittlePaimon | [资源检查]开始检查资源
03-07 15:43:24 [INFO] LittlePaimon | [资源检查]资源完好，无需下载
03-07 15:43:24 [INFO] LittlePaimon | [Playwright]正在安装 chromium
03-07 15:43:24 [INFO] LittlePaimon | [Playwright]正在安装依赖
/usr/lib/python3.8/site-packages/playwright/driver/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /usr/lib/python3.8/site-packages/playwright/driver/node)
/usr/lib/python3.8/site-packages/playwright/driver/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/python3.8/site-packages/playwright/driver/node)
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
03-07 15:43:25 [ERROR] uvicorn | Traceback (most recent call last):
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 19, in init
    _browser = await launch_browser(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 30, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 14007, in launch
    await self._impl_obj.launch(
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-jl581i --remote-debugging-pipe --no-startup-window
<launched> pid=30863
[pid=30863][err] /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
[pid=30863] <process did exit: exitCode=127, signal=null>
[pid=30863] starting temporary directories cleanup
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-jl581i --remote-debugging-pipe --no-startup-window
<launched> pid=30863
[pid=30863][err] /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
[pid=30863] <process did exit: exitCode=127, signal=null>
[pid=30863] starting temporary directories cleanup
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 53, in start_browser
    await get_browser(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 34, in get_browser
    return _browser or await init(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 24, in init
    _browser = await launch_browser(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 30, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 14007, in launch
    await self._impl_obj.launch(
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-Xnps3T --remote-debugging-pipe --no-startup-window
<launched> pid=30897
[pid=30897][err] /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
[pid=30897] <process did exit: exitCode=127, signal=null>
[pid=30897] starting temporary directories cleanup
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-Xnps3T --remote-debugging-pipe --no-startup-window
<launched> pid=30897
[pid=30897][err] /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
[pid=30897] <process did exit: exitCode=127, signal=null>
[pid=30897] starting temporary directories cleanup
============================================================

03-07 15:43:25 [ERROR] uvicorn | Application startup failed. Exiting.

弄了3个小时，在网上找了各种办法都没解决，如果运行nb paimon run playwright install chromium --with-deps
不直接运行run，又会出现get-apt 找不到，不知道怎么处理了，希望有时间麻烦看看，

**Comment by Ventsze** [comment]
怎么字这么大...
03-07 15:43:22 [SUCCESS] LittlePaimon | [数据库]连接成功
03-07 15:43:23 [SUCCESS] LittlePaimon | [插件管理器]初始化完成
03-07 15:43:23 [INFO] LittlePaimon | [资源检查]开始检查资源
03-07 15:43:24 [INFO] LittlePaimon | [资源检查]资源完好，无需下载
03-07 15:43:24 [INFO] LittlePaimon | [Playwright]正在安装 chromium
03-07 15:43:24 [INFO] LittlePaimon | [Playwright]正在安装依赖
/usr/lib/python3.8/site-packages/playwright/driver/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /usr/lib/python3.8/site-packages/playwright/driver/node)
/usr/lib/python3.8/site-packages/playwright/driver/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/python3.8/site-packages/playwright/driver/node)
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
03-07 15:43:25 [ERROR] uvicorn | Traceback (most recent call last):
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 19, in init
    _browser = await launch_browser(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 30, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 14007, in launch
    await self._impl_obj.launch(
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-jl581i --remote-debugging-pipe --no-startup-window
<launched> pid=30863
[pid=30863][err] /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
[pid=30863] <process did exit: exitCode=127, signal=null>
[pid=30863] starting temporary directories cleanup
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-jl581i --remote-debugging-pipe --no-startup-window
<launched> pid=30863
[pid=30863][err] /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
[pid=30863] <process did exit: exitCode=127, signal=null>
[pid=30863] starting temporary directories cleanup
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 53, in start_browser
    await get_browser(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 34, in get_browser
    return _browser or await init(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 24, in init
    _browser = await launch_browser(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/LittlePaimon/utils/brower.py", line 30, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 14007, in launch
    await self._impl_obj.launch(
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/volume1/docker/genshin/LittlePaimon/.venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-Xnps3T --remote-debugging-pipe --no-startup-window
<launched> pid=30897
[pid=30897][err] /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
[pid=30897] <process did exit: exitCode=127, signal=null>
[pid=30897] starting temporary directories cleanup
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-Xnps3T --remote-debugging-pipe --no-startup-window
<launched> pid=30897
[pid=30897][err] /root/.cache/ms-playwright/chromium-1041/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
[pid=30897] <process did exit: exitCode=127, signal=null>
[pid=30897] starting temporary directories cleanup
============================================================

03-07 15:43:25 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by CMHopeSunshine** [comment]
非主流linux，系统不完整，缺库

**Comment by CMHopeSunshine** [comment]
`BEWARE: your OS is not officially supported by Playwright; downloading fallback build.`
你的操作系统没有被Playwright官方支持

**Comment by Ventsze** [comment]
大佬，那有办法解决吗，我用的nas跑的，因为nas24小时在线...

**Comment by Ventsze** [comment]
群辉nas.

**Comment by Ventsze** [comment]
如果不行我就不折腾了，谢谢

**Comment by CMHopeSunshine** [comment]
恕我没用过nas，如果网上找不到解决方法的话，我也不会。
不过可以试试删除需要用到playwright的插件：把`bot目录/LittlePaimon/utils/broswer.py`文件删掉，删掉后会有些报错类似说`can not import xxx from LittlePaimon.utils.broswer`的，忽略即可

**Comment by Ventsze** [comment]
好，谢谢

**Comment by Ventsze** [comment]
![image](https://user-images.githubusercontent.com/64691133/223428643-68c85f8d-1846-4c84-8af1-c6aabd6b251b.png)
并没有utils目录...

**Comment by CMHopeSunshine** [comment]
LittlePaimon里面

**Comment by Ventsze** [comment]
03-07 16:00:16 [INFO] uvicorn | Application startup complete.
03-07 16:00:16 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:13579 (Press CTRL+C to quit)
这个 已经成功启动了，但是ip访问不了

**Comment by Ventsze** [comment]
http://127.0.0.1:13579/go-cqhttp 这个ip访问不了  防火墙也关了访问不了

**Comment by CMHopeSunshine** [comment]
把127.0.0.1换成你的公网ip啊，127.0.0.1是本地，只能在本地内访问

**Comment by Ventsze** [comment]
我nas是内网 没有公网 内网访问不了

**Comment by Ventsze** [comment]
连路由器上面的

**Comment by CMHopeSunshine** [comment]
那就换成你的内网ip

**Comment by Ventsze** [comment]
好了，犯傻了，谢谢

**Comment by shoucandanghehe** [comment]
为啥不用docker呢🤔
