### ISSUE TITLE
在Linux服务器上部署机器人，在运行nb run时出现以下报错

### ISSUE THREAD

**Issue by LGoLang** [CMHopeSunshine/LittlePaimon#41]
**在Linux服务器上安装机器人时，运行到nb run这一步骤时发生以下报错**

06-04 19:29:49 [SUCCESS] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 17, in <module>
    nonebot.init()
  File "/usr/local/lib/python3.8/site-packages/nonebot/__init__.py", line 228, in init
    config = Config(
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "/usr/local/lib/python3.8/site-packages/nonebot/config.py", line 57, in __call__
    env_file_vars = read_env_file(
  File "pydantic/env_settings.py", line 302, in pydantic.env_settings.read_env_file
  File "/usr/local/lib/python3.8/site-packages/dotenv/main.py", line 366, in dotenv_values
    return DotEnv(
  File "/usr/local/lib/python3.8/site-packages/dotenv/main.py", line 74, in dict
    self._dict = OrderedDict(resolve_variables(raw_values, override=self.override))
  File "/usr/local/lib/python3.8/site-packages/dotenv/main.py", line 231, in resolve_variables
    for (name, value) in values:
  File "/usr/local/lib/python3.8/site-packages/dotenv/main.py", line 82, in parse
    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
  File "/usr/local/lib/python3.8/site-packages/dotenv/main.py", line 24, in with_warn_for_invalid_lines
    for mapping in mappings:
  File "/usr/local/lib/python3.8/site-packages/dotenv/parser.py", line 180, in parse_stream
    reader = Reader(stream)
  File "/usr/local/lib/python3.8/site-packages/dotenv/parser.py", line 71, in __init__
    self.string = stream.read()
  File "/usr/local/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 24: invalid start byte

**然后结束了，本人非相关专业，水平有限，在网上搜索过相关问题后，无法解决，可否指点一下如何解决，如果麻烦的话可以不回复，谢谢。**

**Comment by CMHopeSunshine** [comment]
参考#26

**Comment by LGoLang** [comment]
**感谢大佬，机器人可以运行了，但现在不会回复，能不能提示一下有可能是什么原因呢**
参考教程步骤后续没有改动，运行日志如下，没有后续动作了。

![image](https://user-images.githubusercontent.com/101858522/172021964-b12e8b32-2db4-4237-b4f8-2599df9c4882.png)
![image](https://user-images.githubusercontent.com/101858522/172021985-57d4edfe-884a-4e71-9ef8-decaef123d19.png)

**Comment by CMHopeSunshine** [comment]
> **感谢大佬，机器人可以运行了，但现在不会回复，能不能提示一下有可能是什么原因呢** 参考教程步骤后续没有改动，运行日志如下，没有后续动作了。
> 
> ![image](https://user-images.githubusercontent.com/101858522/172021964-b12e8b32-2db4-4237-b4f8-2599df9c4882.png) ![image](https://user-images.githubusercontent.com/101858522/172021985-57d4edfe-884a-4e71-9ef8-decaef123d19.png)

这是没有加载小派蒙插件，是否已在`bot.py`文件添加`nonebot.load_plugins("LittlePaimon")`？注意不能加在`if __name__=="__main__"`下面，而是加在其上面

**Comment by LGoLang** [comment]
确实是这个问题，我在看教程时直接添加到最下方了，导致没有加载插件，现在正常运行了，谢谢大佬。
![image](https://user-images.githubusercontent.com/101858522/172033850-de37bf9d-70c8-4bd6-8b53-8d5ecdf8aa99.png)
