### ISSUE TITLE
[Bug]无法启动

### ISSUE THREAD

**Issue by lvwenzhuo2003** [CMHopeSunshine/LittlePaimon#415]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-67-generic x86_64)
- Python版本: 3.10.6
- Nonebot2版本: 2.0.0rc3

### 问题描述

启动时报错，随后程序卡死。在尝试poetry install更新后再次启动程序会直接报错退出。

更新前的报错日志
```
03-27 04:22:44 [SUCCESS] nonebot | Running NoneBot...
03-27 04:22:44 [INFO] uvicorn | Started server process [4148680]
03-27 04:22:44 [INFO] uvicorn | Waiting for application startup.
03-27 04:22:44 [INFO] nonebot_plugin_apscheduler | Scheduler Started
03-27 04:22:45 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot_plugin_fortune/config.py", line 126, in fortune_check
    ret = await download_resource(copywriting_path, "copywriting.json", "fortune")
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot_plugin_fortune/download.py", line 47, in download_resource
    version = resp.json().get("version")
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

03-27 04:22:45 [ERROR] uvicorn | Application startup failed. Exiting.
03-27 04:22:45 [ERROR] apscheduler | Job "dy_sched (trigger: date[2023-03-27 04:22:44 CST], next run at: 2023-03-27 04:22:44 CST)" raised an exception
Traceback (most recent call last):
  File "/home/lvwenzhuo/LittlePaimon/bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/usr/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
> File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/haruka_bot/plugins/pusher/dynamic_pusher.py", line 28, in dy_sched
    await asyncio.sleep(1)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError
Killed
```

更新后的报错日志
```
03-27 04:29:53 [SUCCESS] nonebot | Running NoneBot...
03-27 04:29:53 [INFO] uvicorn | Started server process [4149678]
03-27 04:29:53 [INFO] uvicorn | Waiting for application startup.
03-27 04:29:54 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot_plugin_fortune/config.py", line 126, in fortune_check
    ret = await download_resource(copywriting_path, "copywriting.json", "fortune")
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot_plugin_fortune/download.py", line 47, in download_resource
    version = resp.json().get("version")
  File "/home/lvwenzhuo/LittlePaimon/.venv/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

03-27 04:29:54 [ERROR] uvicorn | Application startup failed. Exiting.
```

### 问题截图

提供问题或日志截图...

### 复现步骤[可选]

描述问题复现过程...

**Comment by lvwenzhuo2003** [comment]
问题已解决，是不兼容的插件
