### ISSUE TITLE
[问题]不是有效win32应用程序

### ISSUE THREAD

**Issue by YouYouLip** [CMHopeSunshine/LittlePaimon#420]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows11
- Python版本: 3.10.9
- Nonebot2版本: 2.0.0rc4(example)

### 问题描述

简单的描述问题发生过程或表现...

### 问题截图
04-07 19:09:30 [ERROR] nonebot | Failed to import "Paimon_Wiki"
Traceback (most recent call last):
  File "D:\NoneBot-LingYin\LittlePaimon\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\__init__.py", line 33, in <module>
    from .draw_map import init_map, draw_map, get_full_map
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\draw_map.py", line 11, in <module>
    from .genshinmap import utils, models, request, img, XYPoint
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\genshinmap\img.py", line 6, in <module>
    from sklearn.cluster import KMeans
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\sklearn\base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\sklearn\utils\__init__.py", line 17, in <module>
    from scipy.sparse import issparse
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\scipy\sparse\__init__.py", line 283, in <module>
    from . import csgraph
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\scipy\sparse\csgraph\__init__.py", line 182, in <module>
    from ._laplacian import laplacian
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\scipy\sparse\csgraph\_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\scipy\sparse\linalg\__init__.py", line 120, in <module>
    from ._isolve import *
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\scipy\sparse\linalg\_isolve\__init__.py", line 4, in <module>
    from .iterative import *
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\scipy\sparse\linalg\_isolve\iterative.py", line 9, in <module>
    from . import _iterative
ImportError: DLL load failed while importing _iterative: %1 不是有效的 Win32 应用程序。

### 复现步骤[可选]

描述问题复现过程...

**Comment by YouYouLip** [comment]
感觉像是安装了某个插件的问题 这个问题出现前我用的是win10 安了部分插件并没有报错，但是更新了win11之后安装了插件出现了这个报错

**Comment by CMHopeSunshine** [comment]
系统依赖库问题，请自行搜索解决

**Comment by YouYouLip** [comment]
> 系统依赖库问题，请自行搜索解决

说实话我找不到了.... vc运行库我都安了

**Comment by YouYouLip** [comment]
> 系统依赖库问题，请自行搜索解决

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: D:\1\LittlePaimon\.venv\Scripts\python.exe -m pip install --upgrade pip
[?] go-cqhttp安装和使用方式? 我已安装或稍候自行安装
安装完成!
运行以下命令来启动你的小派蒙:
  cd LittlePaimon
  nb paimon run
开始享用小派蒙吧!
PS D:\1> cd littlepaimon
PS D:\1\littlepaimon> nb paimon run
使用虚拟环境: D:\1\LittlePaimon\.venv\Scripts\python.exe
04-07 20:58:39 [SUCCESS] nonebot | NoneBot is initializing...
04-07 20:58:39 [INFO] nonebot | Current Env: prod
04-07 20:58:47 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Wiki" from "LittlePaimon.plugins.Paimon_Wiki"
04-07 20:58:47 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Bind" from "LittlePaimon.plugins.Paimon_Bind"
04-07 20:58:48 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Autobbs" from "LittlePaimon.plugins.Paimon_Autobbs"
04-07 20:58:48 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Gacha" from "LittlePaimon.plugins.Paimon_Gacha"
04-07 20:58:48 [SUCCESS] nonebot | Succeeded to load plugin "Genshin_Voice" from "LittlePaimon.plugins.Genshin_Voice"
04-07 20:58:48 [SUCCESS] nonebot | Succeeded to load plugin "tools" from "LittlePaimon.plugins.tools"
04-07 20:58:48 [SUCCESS] nonebot | Succeeded to load plugin "news60s" from "LittlePaimon.plugins.news60s"
04-07 20:58:48 [SUCCESS] nonebot | Succeeded to load plugin "Mihoyo_bbs" from "LittlePaimon.plugins.Mihoyo_bbs"
04-07 20:58:48 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_CloudGenshin" from "LittlePaimon.plugins.Paimon_CloudGenshin"
04-07 20:58:49 [SUCCESS] nonebot | Succeeded to load plugin "plugin_manager" from "LittlePaimon.plugins.plugin_manager"
04-07 20:58:49 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Abyss" from "LittlePaimon.plugins.Paimon_Abyss"
04-07 20:58:49 [SUCCESS] nonebot | Succeeded to load plugin "bot_manager" from "LittlePaimon.plugins.bot_manager"
04-07 20:58:49 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Info" from "LittlePaimon.plugins.Paimon_Info"
04-07 20:58:50 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_DailyNote" from "LittlePaimon.plugins.Paimon_DailyNote"
04-07 20:58:51 [SUCCESS] nonebot | Succeeded to load plugin "Learning_Chat" from "LittlePaimon.plugins.Learning_Chat"
04-07 20:58:51 [SUCCESS] nonebot | Succeeded to load plugin "Genshin_Calendar" from "LittlePaimon.plugins.Genshin_Calendar"
04-07 20:58:51 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_MonthInfo" from "LittlePaimon.plugins.Paimon_MonthInfo"
04-07 20:58:51 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Gacha_Log" from "LittlePaimon.plugins.Paimon_Gacha_Log"
04-07 20:58:51 [SUCCESS] nonebot | Succeeded to load plugin "NoticeAndRequest" from "LittlePaimon.plugins.NoticeAndRequest"
04-07 20:58:51 [SUCCESS] nonebot | Succeeded to load plugin "LittlePaimon"
04-07 20:58:51 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
04-07 20:58:51 [SUCCESS] nonebot | Running NoneBot...
04-07 20:58:51 [INFO] uvicorn | Started server process [2656]
04-07 20:58:51 [INFO] uvicorn | Waiting for application startup.
04-07 20:58:51 [INFO] LittlePaimon | Scheduler Started
04-07 20:58:51 [INFO] LittlePaimon | [Web UI]启用成功，默认地址为http://127.0.0.1:13579/LittlePaimon/login
04-07 20:58:51 [INFO] LittlePaimon |
██╗     ██╗████████╗████████╗██╗     ███████╗  ██████╗  █████╗ ██╗███╗   ███╗ ██████╗ ███╗   ██╗
██║     ██║╚══██╔══╝╚══██╔══╝██║     ██╔════╝  ██╔══██╗██╔══██╗██║████╗ ████║██╔═══██╗████╗  ██║
██║     ██║   ██║      ██║   ██║     █████╗    ██████╔╝███████║██║██╔████╔██║██║   ██║██╔██╗ ██║
██║     ██║   ██║      ██║   ██║     ██╔══╝    ██╔═══╝ ██╔══██║██║██║╚██╔╝██║██║   ██║██║╚██╗██║
███████╗██║   ██║      ██║   ███████╗███████╗  ██║     ██║  ██║██║██║ ╚═╝ ██║╚██████╔╝██║ ╚████║
╚══════╝╚═╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝  ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
04-07 20:58:52 [SUCCESS] LittlePaimon | [数据库]连接成功
04-07 20:58:52 [SUCCESS] LittlePaimon | [插件管理器]初始化完成
04-07 20:58:52 [INFO] LittlePaimon | [资源检查]开始检查资源
resources.zip:   0%|▏                                                              | 195k/76.4M [00:01<05:11, 256kiB/s]04-07 20:58:56 [INFO] LittlePaimon | [Playwright]浏览器初始化成功
04-07 20:58:56 [INFO] uvicorn | Application startup complete.
04-07 20:58:56 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:13579 (Press CTRL+C to quit)
resources.zip:  10%|██████▎                                                       | 7.83M/76.4M [00:22<02:18, 520kiB/s]

新开的一个bot 未装任何插件可以完美运行 so.....不会真是插件的事吧

**Comment by YouYouLip** [comment]
问题暂时解决 重新从git拷贝过来重新部署并且重新安装插件后无报错，但愿能一直没有吧
