### ISSUE TITLE
[问题]yml语法错误

### ISSUE THREAD

**Issue by m1060748088** [CMHopeSunshine/LittlePaimon#427]
### 问题描述

LittlePaimon>poetry run nb run
04-20 11:29:10 [SUCCESS] nonebot | NoneBot is initializing...
04-20 11:29:10 [INFO] nonebot | Current Env: prod
04-20 11:29:11 [ERROR] nonebot | Failed to import "LittlePaimon"
Traceback (most recent call last):
  File "C:\Users\dell\LittlePaimon\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\dell\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-b6iKLH58-py3.9\lib\site-packages\nonebot\plugin\load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\dell\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-b6iKLH58-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\dell\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-b6iKLH58-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\dell\LittlePaimon\LittlePaimon\__init__.py", line 5, in <module>
    from LittlePaimon import database, web
  File "C:\Users\dell\LittlePaimon\LittlePaimon\web\__init__.py", line 5, in <module>
    from LittlePaimon.config import config
  File "C:\Users\dell\LittlePaimon\LittlePaimon\config\__init__.py", line 2, in <module>
    from .plugin.manage import PluginManager, HIDDEN_PLUGINS, MatcherInfo, PluginInfo
  File "C:\Users\dell\LittlePaimon\LittlePaimon\config\plugin\manage.py", line 29, in <module>
    class PluginManager:
  File "C:\Users\dell\LittlePaimon\LittlePaimon\config\plugin\manage.py", line 33, in PluginManager
    data = load_yaml(file)
  File "C:\Users\dell\LittlePaimon\LittlePaimon\utils\files.py", line 74, in load_yaml
    return yaml.load(path.read_text(encoding=encoding),
  File "C:\Users\dell\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-b6iKLH58-py3.9\lib\site-packages\ruamel\yaml\main.py", line 1069, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)  # type: Any
  File "C:\Users\dell\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-b6iKLH58-py3.9\lib\site-packages\ruamel\yaml\loader.py", line 50, in __init__
    Reader.__init__(self, stream, loader=self)
  File "C:\Users\dell\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-b6iKLH58-py3.9\lib\site-packages\ruamel\yaml\reader.py", line 88, in __init__
    self.stream = stream  # type: Any  # as .read is called
  File "C:\Users\dell\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-b6iKLH58-py3.9\lib\site-packages\ruamel\yaml\reader.py", line 120, in stream
    self.check_printable(val)
  File "C:\Users\dell\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-b6iKLH58-py3.9\lib\site-packages\ruamel\yaml\reader.py", line 244, in check_printable
    raise ReaderError(
ruamel.yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "<unicode string>", position 0
04-20 11:29:11 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
04-20 11:29:11 [SUCCESS] nonebot | Running NoneBot...
04-20 11:29:11 [INFO] uvicorn | Started server process [13204]
04-20 11:29:11 [INFO] uvicorn | Waiting for application startup.
04-20 11:29:11 [INFO] LittlePaimon | Scheduler Started
04-20 11:29:11 [INFO] uvicorn | Application startup complete.
04-20 11:29:11 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:13579 (Press CTRL+C to quit)

### 问题截图

![image](https://user-images.githubusercontent.com/60548015/233251178-8698c713-d64d-4ce3-a931-a45a254c25e5.png)

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
`ruamel.yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
in "", position 0`
检查你的`bot目录/config`里的yml文件，其中一个语法错误

**Comment by m1060748088** [comment]
谢谢大佬！
我把所有bot目录/config里面所有yml文件都还原成一个月前备份了，bot可以启动运行了。
