### ISSUE TITLE
生成地图时出错

### ISSUE THREAD

**Issue by KeepingRunning** [CMHopeSunshine/LittlePaimon#438]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.10.11(example)
- Nonebot2版本: V1.01

### 问题截图

提供问题或日志截图...
05-24 00:14:35 [ERROR] nonebot | Running Matcher(type='message', module=LittlePaimon.plugins.Paimon_Wiki) failed.
Traceback (most recent call last):
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "D:\python\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\anyio\streams\tls.py", line 151, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpcore\_async\http_proxy.py", line 289, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 66, in start_tls
    with map_exceptions(exc_map):
  File "D:\python\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\python\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
 File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\__init__.py", line 181, in _
    result = await init_map()
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\draw_map.py", line 45, in init_map
    map_img = await utils.make_map(maps.detail)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\genshinmap\utils.py", line 44, in make_map
    maps: List[Image.Image] = await gather(
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\LittlePaimon\plugins\Paimon_Wiki\genshinmap\utils.py", line 16, in get_img
    resp = await CLIENT.get(url)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "D:\python\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\.GIVE_ME_AN_OFFER\bot\littlepaimon\LittlePaimon\.venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

**Comment by CMHopeSunshine** [comment]
网络问题，如开了代理，请关闭代理

**Comment by KeepingRunning** [comment]
解决了，谢谢
