### ISSUE TITLE
[问题]插件”原神实时便签“未加载，功能不可用

### ISSUE THREAD

**Issue by Rorschachina** [CMHopeSunshine/LittlePaimon#444]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Ubuntu 22.04.2，使用Docker 23.0.1部署
- Python版本: 3.10
- Nonebot2版本: 2.0.0rc4

### 问题描述

插件”原神实时便签“未加载，功能不可用

### 问题截图

<img width="407" alt="image" src="https://github.com/CMHopeSunshine/LittlePaimon/assets/31760466/fc78339f-6ff2-4d2b-af4d-d6e961e52e31">

### 复现步骤[可选]

不太清楚什么时候出现的，之前有段时间因为米哈游异常检测得厉害，我就关了一段时间，昨天打开的时候发现插件不能用了，在插件管理中看就是未加载。

小派蒙的版本已经更新至最新版，依赖也是，甚至尝试过卸载并重新安装所有依赖，也不行，只有这一个插件加载失败，其他都是好的。
小派蒙启动时会报错，插件加载失败，具体错误内容如下：

```
05-30 10:40:52 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Info" from "LittlePaimon.plugins.Paimon_Info"
05-30 10:40:52 [ERROR] nonebot | Failed to import "Paimon_DailyNote"
Traceback (most recent call last):
  File "/app/LittlePaimon/bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/LittlePaimon/LittlePaimon/__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/LittlePaimon/LittlePaimon/plugins/Paimon_DailyNote/__init__.py", line 11, in <module>
    from .handler import SubList, get_subs, handle_ssbq
  File "/app/LittlePaimon/LittlePaimon/plugins/Paimon_DailyNote/handler.py", line 78, in <module>
    async def check_note():
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 470, in inner
    self.add_job(func, trigger, args, kwargs, id, name, misfire_grace_time, coalesce,
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 424, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 925, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 910, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/apscheduler/triggers/cron/__init__.py", line 83, in __init__
    field = field_class(field_name, exprs, is_default)
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/apscheduler/triggers/cron/fields.py", line 33, in __init__
    self.compile_expressions(exprs)
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/apscheduler/triggers/cron/fields.py", line 58, in compile_expressions
    self.compile_expression(expr)
  File "/app/LittlePaimon/.venv/lib/python3.10/site-packages/apscheduler/triggers/cron/fields.py", line 70, in compile_expression
    six.raise_from(exc, None)
  File "<string>", line 3, in raise_from
ValueError: Error validating expression '*/60': the step value (60) is higher than the total range of the expression (59)
05-30 10:40:52 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Gacha_Log" from "LittlePaimon.plugins.Paimon_Gacha_Log"
05-30 10:40:52 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Abyss" from "LittlePaimon.plugins.Paimon_Abyss"
```

**Comment by CMHopeSunshine** [comment]
看报错提示，检查间隔分钟不能超过60

**Comment by CMHopeSunshine** [comment]
另外现在依然不建议开启定时检查，验证码还是很多，频繁检查的话有ban ip的可能

**Comment by Rorschachina** [comment]
感谢大佬，确实是配置的问题，改了下就好了
