### ISSUE TITLE
[问题]"Learning_Chat"报错

### ISSUE THREAD

**Issue by YouYouLip** [CMHopeSunshine/LittlePaimon#447]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows11(example)
- Python版本: 3.9.10(example)
- Nonebot2版本: 2.0.0rc4(example)

### 问题描述
06-12 01:43:17 [ERROR] nonebot | Failed to import "Learning_Chat"
Traceback (most recent call last):
  File "D:\NoneBot-LingYin\LittlePaimon\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\plugins\Learning_Chat\__init__.py", line 16, in <module>
    from . import web_api, web_page
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\plugins\Learning_Chat\web_page.py", line 406, in <module>
    listItem=AmisList.Item(body=[AmisList.Item.ListBodyField(name="msg")]),
AttributeError: type object 'Item' has no attribute 'ListBodyField'
.

### 复现步骤[可选]
更新后出现的问题

**Comment by CMHopeSunshine** [comment]
更新版本(进入虚拟环境后) pip install amis-python -U

**Comment by YouYouLip** [comment]
> 更新版本(进入虚拟环境后) pip install amis-python -U

谢谢 已解决
