### ISSUE TITLE
[问题]更新失败，本地修改过文件导致冲突，请解决冲突后再更新。

### ISSUE THREAD

**Issue by YouYouLip** [CMHopeSunshine/LittlePaimon#455]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows11(example)
- Python版本: 3.9.10(example)
- Nonebot2版本: 2.0.0rc4(example)

### 问题描述

使用机器人自带的更新指令会出现这种错误

### 问题截图

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/119958263/5209f059-fd9e-4d68-9abf-e28852722e90)

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
这不是说的很清楚吗？**本地修改过文件导致冲突，请解决冲突后再更新**

**Comment by YouYouLip** [comment]
> 这不是说的很清楚吗？**本地修改过文件导致冲突，请解决冲突后再更新**

主要是不清楚是哪一个...有没有具体范围啊

**Comment by YouYouLip** [comment]
> 这不是说的很清楚吗？**本地修改过文件导致冲突，请解决冲突后再更新**

更主要的是我印象中我也没改过什么文件

**Comment by CMHopeSunshine** [comment]
在命令行里运行`git pull`来看

**Comment by YouYouLip** [comment]
> 在命令行里运行`git pull`来看

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/119958263/ffde1ecd-973d-46c8-b5bd-d55bb6a6d025)
冲突的是这两个 我把这两个在我本地的删除了后拷贝了一个仓库新的文件后还是这个报错

**Comment by YouYouLip** [comment]
> 在命令行里运行`git pull`来看

我看了一眼 一个是面板计算有关 另一个是资源检查文件

**Comment by CMHopeSunshine** [comment]
删了就行，别拷贝新的

**Comment by YouYouLip** [comment]
> 删了就行，别拷贝新的

嗯....更新问题是解决了 但是更新后使用检查更新这个指令又有新报错了（雾）
06-20 17:35:18 [ERROR] nonebot | Running Matcher(type='message', module=LittlePaimon.plugins.bot_manager) failed.
Traceback (most recent call last):
  File "D:\NoneBot-LingYin\LittlePaimon\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\plugins\bot_manager\__init__.py", line 114, in _
    result = await check_update()
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\utils\update.py", line 15, in check_update
    resp = await aiorequests.get('https://api.github.com/repos/CMHopeSunshine/LittlePaimon/commits')
  File "D:\NoneBot-LingYin\LittlePaimon\LittlePaimon\utils\requests.py", line 31, in get
    return await client.get(url,
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\33034\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

**Comment by CMHopeSunshine** [comment]
SSL证书验证问题，可能是你的梯子不行。

**Comment by CMHopeSunshine** [comment]
另外，要更新的话，直接命令行运行`git pull`比用bot指令更新信息要更明确，建议用命令行
