### ISSUE TITLE
[建议] 将小派蒙插件化以方便缝合

### ISSUE THREAD

**Issue by sgpublic** [CMHopeSunshine/LittlePaimon#474]
### 当前不足

目前的部署方式似乎只适合单独部署，如果想实现添加插件就不太好更新。

我目前的解决方案是写了一堆wrapper，然后小派蒙作为submodule放到src目录，这样更新就只需要git submodule update就行，这样就能随意添加其他插件。

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/37202870/0b162b7a-0a02-49e8-81c6-4e9c78c86d62)

但这样会出很多未知的问题（特别是循环依赖），难以维护：

```
nonebot-little-paimon  | 09-27 04:41:30 [ERROR] nonebot | Failed to import "LittlePaimon-plugin-NahidaCalc"
nonebot-little-paimon  | Traceback (most recent call last):
nonebot-little-paimon  |   File "<string>", line 12, in <module>
nonebot-little-paimon  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/littlepaimonwrapper-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
nonebot-little-paimon  |     return load_all_plugins(plugins, plugin_dirs)
nonebot-little-paimon  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/littlepaimonwrapper-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
nonebot-little-paimon  |     return manager.load_all_plugins()
nonebot-little-paimon  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/littlepaimonwrapper-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
nonebot-little-paimon  |     return set(
nonebot-little-paimon  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/littlepaimonwrapper-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
nonebot-little-paimon  |     filter(None, (self.load_plugin(name) for name in self.available_plugins))
nonebot-little-paimon  | > File "/home/poetry-runner/.cache/pypoetry/virtualenvs/littlepaimonwrapper-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 146, in load_plugin
nonebot-little-paimon  |     module = importlib.import_module(
nonebot-little-paimon  |   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
nonebot-little-paimon  |     return _bootstrap._gcd_import(name[level:], package, level)
nonebot-little-paimon  |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
nonebot-little-paimon  |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
nonebot-little-paimon  |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
nonebot-little-paimon  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
nonebot-little-paimon  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/littlepaimonwrapper-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
nonebot-little-paimon  |     super().exec_module(module)
nonebot-little-paimon  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
nonebot-little-paimon  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nonebot-little-paimon  |   File "/app/plugins/LittlePaimon-plugin-NahidaCalc/__init__.py", line 13, in <module>
nonebot-little-paimon  |     from LittlePaimon.utils import DRIVER, logger
nonebot-little-paimon  |   File "/app/LittlePaimon/__init__.py", line 1, in <module>
nonebot-little-paimon  |     from LittlePaimon.utils import NICKNAME, SUPERUSERS, __version__
nonebot-little-paimon  |   File "/app/LittlePaimon/utils/__init__.py", line 1, in <module>
nonebot-little-paimon  |     from src.LittlePaimon.utils import logger, DRIVER, __version__, NICKNAME, SUPERUSERS
nonebot-little-paimon  |   File "/app/src/LittlePaimon/__init__.py", line 5, in <module>
nonebot-little-paimon  |     from LittlePaimon import database, web
nonebot-little-paimon  |   File "/app/LittlePaimon/database/__init__.py", line 1, in <module>
nonebot-little-paimon  |     from src.LittlePaimon.database import DATABASE, register_database, connect, disconnect, daily_reset, LastQuery, Player
nonebot-little-paimon  |   File "/home/poetry-runner/.cache/pypoetry/virtualenvs/littlepaimonwrapper-9TtSrW0h-py3.11/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
nonebot-little-paimon  |     super().exec_module(module)
nonebot-little-paimon  |   File "/app/src/LittlePaimon/database/__init__.py", line 6, in <module>
nonebot-little-paimon  |     from LittlePaimon.utils import scheduler, logger as my_logger
nonebot-little-paimon  | ImportError: cannot import name 'logger' from partially initialized module 'LittlePaimon.utils' (most likely due to a circular import) (/app/LittlePaimon/utils/__init__.py)
```

### 建议内容

既然目前小派梦已经趋于稳定，可以考虑将小派蒙插件化，安装插件即可运行。

### 参考示例[可选]

例如 [HarukaBot](https://github.com/SK-415/HarukaBot)，既可以单独部署又可以插件安装。

**Comment by CMHopeSunshine** [comment]
正在编写下一个大版本，原神和星铁功能都会拆开做成插件形式，当前这个版本不会再有大改动了，~~敬请期待吧））~~

**Comment by sgpublic** [comment]
> 正在编写下一个大版本，原神和星铁功能都会拆开做成插件形式，当前这个版本不会再有大改动了，~敬请期待吧））~

好耶，大佬nb！
