### ISSUE TITLE
[问题]LittlePaimon/login 无法访问

### ISSUE THREAD

**Issue by xuewuerduo** [CMHopeSunshine/LittlePaimon#497]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Ubuntu
- Python版本: 3.8.10
- Nonebot2版本: latest

### 问题描述

小派蒙启动报错，LittlePaimon/login 无法访问，go-cqhttp页面正常

### 问题截图

>root@mail:/opt/data/Paimon# nb paimon
██╗     ██╗████████╗████████╗██╗     ███████╗  ██████╗  █████╗ ██╗███╗   ███╗ ██████╗ ███╗   ██╗
██║     ██║╚══██╔══╝╚══██╔══╝██║     ██╔════╝  ██╔══██╗██╔══██╗██║████╗ ████║██╔═══██╗████╗  ██║
██║     ██║   ██║      ██║   ██║     █████╗    ██████╔╝███████║██║██╔████╔██║██║   ██║██╔██╗ ██║
██║     ██║   ██║      ██║   ██║     ██╔══╝    ██╔═══╝ ██╔══██║██║██║╚██╔╝██║██║   ██║██║╚██╗██║
███████╗██║   ██║      ██║   ███████╗███████╗  ██║     ██║  ██║██║██║ ╚═╝ ██║╚██████╔╝██║ ╚████║
╚══════╝╚═╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝  ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
欢迎来到小派蒙的Nonebot CLI 插件!
[?] 你想要进行什么操作? 运行命令或启动小派蒙Bot.
使用虚拟环境: /opt/data/Paimon/.venv/bin/python
01-24 11:44:45 [SUCCESS] nonebot | NoneBot is initializing...
01-24 11:44:45 [INFO] nonebot | Current Env: prod
01-24 11:44:46 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_gocqhttp"
01-24 11:44:46 [ERROR] nonebot | Failed to import "LittlePaimon"
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/data/Paimon/LittlePaimon/__init__.py", line 5, in <module>
    from LittlePaimon import database, web
  File "/opt/data/Paimon/LittlePaimon/database/__init__.py", line 6, in <module>
    from LittlePaimon.utils import scheduler, logger as my_logger
  File "/opt/data/Paimon/LittlePaimon/utils/__init__.py", line 5, in <module>
    from .scheduler import scheduler
  File "/opt/data/Paimon/LittlePaimon/utils/scheduler.py", line 24, in <module>
    scheduler = AsyncIOScheduler()
  File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 97, in __init__
    self.configure(gconfig, **options)
  File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 141, in configure
    self._configure(config)
  File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/apscheduler/schedulers/asyncio.py", line 46, in _configure
    super(AsyncIOScheduler, self)._configure(config)
  File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 711, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/tzlocal/unix.py", line 219, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/tzlocal/unix.py", line 180, in _get_localzone
    tzname = _get_localzone_name(_root)
  File "/opt/data/Paimon/.venv/lib/python3.8/site-packages/tzlocal/unix.py", line 159, in _get_localzone_name
    raise zoneinfo.ZoneInfoNotFoundError(message)
backports.zoneinfo._common.ZoneInfoNotFoundError: 'Multiple conflicting time zone configurations found:\n/etc/timezone: Etc/UTC\n/etc/localtime is a symlink to: Asia/Shanghai\nFix the configuration, or set the time zone in a TZ environment variable.\n'
01-24 11:44:46 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
01-24 11:44:46 [SUCCESS] nonebot | Running NoneBot...
01-24 11:44:46 [INFO] uvicorn | Started server process [479565]
01-24 11:44:46 [INFO] uvicorn | Waiting for application startup.
01-24 11:44:46 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://0.0.0.0:13579/go-cqhttp/
01-24 11:44:46 [INFO] uvicorn | Application startup complete.
01-24 11:44:46 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:13579 (Press CTRL+C to quit)

**Comment by CMHopeSunshine** [comment]
**'Multiple conflicting time zone configurations found:\n/etc/timezone: Etc/UTC\n/etc/localtime is a symlink to: Asia/Shanghai\nFix the configuration, or set the time zone in a TZ environment variable.**

**Comment by xuewuerduo** [comment]
哦哦，解决了，感谢大佬！我一直以为上面哪里不对。。。
