### ISSUE TITLE
[问题]插件“星铁面板”未加载，不可用

### ISSUE THREAD

**Issue by AratoEndo** [CMHopeSunshine/LittlePaimon#502]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows11
- Python版本: 3.10.11
- Nonebot2版本: 2.0.0rc4

### 问题描述

插件“星铁面板”未加载，不可用

### 问题截图

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/138769041/29dd603b-81f0-4e87-802d-3efa3caaf293)

### 复现步骤[可选]

03-14 04:45:50 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_CloudGenshin" from "LittlePaimon.plugins.Paimon_CloudGenshin"
03-14 04:45:51 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Gacha_Log" from "LittlePaimon.plugins.Paimon_Gacha_Log"
03-14 04:45:52 [ERROR] nonebot | Failed to import "Learning_Chat"
Traceback (most recent call last):
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Server\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\LittlePaimon\plugins\Learning_Chat\__init__.py", line 16, in <module>
    from . import web_api, web_page
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\LittlePaimon\plugins\Learning_Chat\web_page.py", line 406, in <module>
    listItem=AmisList.Item(body=[AmisList.Item.ListBodyField(name="msg")]),
AttributeError: type object 'Item' has no attribute 'ListBodyField'
03-14 04:45:52 [SUCCESS] nonebot | Succeeded to load plugin "Genshin_Calendar" from "LittlePaimon.plugins.Genshin_Calendar"
03-14 04:45:52 [SUCCESS] nonebot | Succeeded to load plugin "plugin_manager" from "LittlePaimon.plugins.plugin_manager"
03-14 04:45:52 [SUCCESS] nonebot | Succeeded to load plugin "news60s" from "LittlePaimon.plugins.news60s"
03-14 04:45:52 [ERROR] nonebot | Failed to import "star_rail_info"
Traceback (most recent call last):
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\LittlePaimon\__init__.py", line 46, in <module>
    load_plugins(str(Path(__file__).parent / 'plugins'))
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Server\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\LittlePaimon\plugins\star_rail_info\__init__.py", line 5, in <module>
    from nonebot.adapters.onebot.utils import rich_unescape
ImportError: cannot import name 'rich_unescape' from 'nonebot.adapters.onebot.utils' (C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony\.venv\Lib\site-packages\nonebot\adapters\onebot\utils.py)
03-14 04:45:52 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_Wiki" from "LittlePaimon.plugins.Paimon_Wiki"
03-14 04:45:52 [SUCCESS] nonebot | Succeeded to load plugin "Paimon_DailyNote" from "LittlePaimon.plugins.Paimon_Dail

**Comment by CMHopeSunshine** [comment]
> ImportError: cannot import name 'rich_unescape' from 'nonebot.adapters.onebot.utils' (C:\Users\Server\Desktop\bot\little paimeng\LittlePaimony.venv\Lib\site-packages\nonebot\adapters\onebot\utils.py)

看看 nonebot-adapter-onebot 的版本号，升级到最新
