### ISSUE TITLE
[问题]无法启动

### ISSUE THREAD

**Issue by vvb7456** [CMHopeSunshine/LittlePaimon#519]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10 & Ubuntu 22.04 LTS
- Python版本: 3.10

### 问题描述

无法下载额外资源 也无法启动LittlePaimon 
下载资源时提示`下载原神立绘资源时出错: File is not a zip file`
启动时提示`No available download mirror found.`
尝试使用全局代理 或内置镜像故障均一致

### 问题截图
Windows
```
09-24 00:20:54 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\starlette\routing.py", line 738, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Program Files\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Program Files\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 156, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Program Files\Python310\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 41, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Program Files\Python310\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 35, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Program Files\Python310\lib\site-packages\nonebot_plugin_gocqhttp\__init__.py", line 41, in startup
    await download_gocq()
  File "C:\Program Files\Python310\lib\site-packages\nonebot_plugin_gocqhttp\process\download.py", line 120, in download_gocq
    raise RuntimeError("No available download mirror found.")
RuntimeError: No available download mirror found.

09-24 00:20:54 [ERROR] uvicorn | Application startup failed. Exiting.
```

Linux
![122](https://github.com/user-attachments/assets/50a7207d-97a4-4783-8303-8fd26503e75e)

### 复现步骤[可选]

描述问题复现过程...

**Comment by nicklly** [comment]
移除gocq插件 另外建议使用无头nqq保证其稳定性

**Comment by sunnywinds** [comment]
你解决了吗，我遇到了一样的问题。我把gocq的插件删除了之后虽然不会提示`No available download mirror found.`，但启动后无法连接gocq。我尝试用TRSS安装，进入WEB后依旧无法连接gocq。关于资源下载的问题我也没找到解决方案。

**Comment by nicklly** [comment]
> 你解决了吗，我遇到了一样的问题。我把gocq的插件删除了之后虽然不会提示`No available download mirror found.`，但启动后无法连接gocq。我尝试用TRSS安装，进入WEB后依旧无法连接gocq。关于资源下载的问题我也没找到解决方案。

不建议甚至不推荐使用gocq 建议使用ntqq或者基于ntqq开发的napcat来搭配使用 稳定性比gocq强 而且qsign貌似已经全部失效了
