### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by WindraiteLesd** [CMHopeSunshine/LittlePaimon#60]
` uvicorn | Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\ProgramData\Anaconda3\envs\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\ProgramData\Anaconda3\envs\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\Administrator\Desktop\NoneBot2\LittlePaimon\Paimon_Chat\__init__.py", line 88, in load_voice
    voice_list = await load_json_from_url('https://static.cherishmoon.fun/LittlePaimon/voice/voice_list.json')
  File "C:\Users\Administrator\Desktop\NoneBot2\LittlePaimon\utils\file_handler.py", line 45, in load_json_from_url
    return resp.json()
  File "C:\ProgramData\Anaconda3\envs\lib\site-packages\httpx\_models.py", line 1516, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "C:\ProgramData\Anaconda3\envs\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\envs\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\envs\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

 [ERROR] uvicorn | Application startup failed. Exiting.`

**Comment by CMHopeSunshine** [comment]
重试一下即可
