### ISSUE TITLE
日历等两个功能报错，同时请问怎么开启机器学习聊天

### ISSUE THREAD

**Issue by mawMOBai** [CMHopeSunshine/LittlePaimon#74]
[root@VM-16-2-centos LittlePaimon]# nb run
06-23 10:17:04 [SUCCESS] nonebot | NoneBot is initializing...
06-23 10:17:04 [INFO] nonebot | Current Env: prod
06-23 10:17:04 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
06-23 10:17:05 [SUCCESS] nonebot | Succeeded to import "Paimon_Exchange"
06-23 10:17:05 [SUCCESS] nonebot | Succeeded to import "order"
06-23 10:17:05 [SUCCESS] nonebot | Succeeded to import "random_img"
06-23 10:17:05 [SUCCESS] nonebot | Succeeded to import "paimon_help"
06-23 10:17:05 [SUCCESS] nonebot | Succeeded to import "news"
06-23 10:17:05 [SUCCESS] nonebot | Succeeded to import "auto_handle"
06-23 10:17:05 [SUCCESS] nonebot | Succeeded to import "couplets"
06-23 10:17:05 [SUCCESS] nonebot | Succeeded to import "Paimon_Plugins"
06-23 10:17:05 [SUCCESS] nonebot | Succeeded to import "Paimon_Wiki"
06-23 10:17:06 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
06-23 10:17:06 [ERROR] nonebot | Failed to import "nonebot_plugin_htmlrender"
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 27, in <module>
    nonebot.load_plugins("LittlePaimon")
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./LittlePaimon/Paimon_Calendar/__init__.py", line 8, in <module>
    from .generate import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./LittlePaimon/Paimon_Calendar/generate.py", line 3, in <module>
    require("nonebot_plugin_htmlrender")
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/load.py", line 163, in require
    plugin = load_plugin(name)
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_htmlrender'
06-23 10:17:06 [ERROR] nonebot | Failed to import "Paimon_Calendar"
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 27, in <module>
    nonebot.load_plugins("LittlePaimon")
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./LittlePaimon/Paimon_Calendar/__init__.py", line 8, in <module>
    from .generate import *
  File "./LittlePaimon/Paimon_Calendar/generate.py", line 3, in <module>
    require("nonebot_plugin_htmlrender")
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/load.py", line 165, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_htmlrender"!
06-23 10:17:06 [WARNING] LittlePaimon | 派蒙机器学习聊天启用失败，尚未配置mongodb连接url
06-23 10:17:06 [SUCCESS] nonebot | Succeeded to import "Paimon_Chat"
06-23 10:17:06 [SUCCESS] nonebot | Succeeded to import "Guess_voice"
06-23 10:17:09 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
06-23 10:17:09 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
06-23 10:17:09 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
06-23 10:17:09 [SUCCESS] nonebot | Running NoneBot...
06-23 10:17:09 [INFO] uvicorn | Started server process [4744]
06-23 10:17:09 [INFO] uvicorn | Waiting for application startup.
06-23 10:17:09 [INFO] nonebot_plugin_apscheduler | Scheduler Started
06-23 10:17:09 [INFO] uvicorn | Application startup complete.
06-23 10:17:09 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:6660 (Press CTRL+C to quit)

**Comment by CMHopeSunshine** [comment]
1、`pip install nonebot-plugin-htmlrender`
2、安装MongoDB数据库，在.env.prod加入paimon_mongodb_url=你的mongodb数据库链接

**Comment by CMHopeSunshine** [comment]
是重复性的问题了，麻烦请看README和类似的issue
