### ISSUE TITLE
重构后用git pull升级不了怎么解决

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#89]
![image](https://user-images.githubusercontent.com/100580891/177045961-e6d2c500-8a47-4f32-a28f-46004aabe1c8.png)

**Comment by CMHopeSunshine** [comment]
把`res`文件夹改名`LittlePaimon`，移到nb目录的`resources`文件夹里

**Comment by forchannot** [comment]
> 把`res`文件夹改名`LittlePaimon`，移到nb目录的`resources`文件夹里

nb目录在哪呀，没找到

**Comment by CMHopeSunshine** [comment]
> > 把`res`文件夹改名`LittlePaimon`，移到nb目录的`resources`文件夹里
> 
> nb目录在哪呀，没找到

nb是指`nonebot`，也就是`bot.py`、`.env.prod`等文件所在的目录

**Comment by forchannot** [comment]
> > > 把`res`文件夹改名`LittlePaimon`，移到nb目录的`resources`文件夹里
> > 
> > 
> > nb目录在哪呀，没找到
> 
> nb是指`nonebot`，也就是`bot.py`、`.env.prod`等文件所在的目录

readme文档中这里似乎有些问题
![Screenshot_2022-07-03-23-54-53-382_mark via](https://user-images.githubusercontent.com/100580891/177047456-27042dce-c6a0-4a69-9cf0-d748f174c08f.png)
通过pip安装的必须要在nonebot目录下的pyproject.toml文件中plugins加入LittilePaimon才能让nb加载插件，单纯添加nonebot.loadxxxx似乎不管用

**Comment by CMHopeSunshine** [comment]
是吗，我尝试一下
果然，感谢指出

**Comment by forchannot** [comment]
> 是吗，我尝试一下

发现个问题，通过pip安装的发啥也没反应，不知道什么东西没加载，Littlepaimon和littlepaimon_utils都加载了

**Comment by CMHopeSunshine** [comment]
> 

试了，写在`pyproject.toml`中才能读取`site-package`中的包，那只能稍作修改了，暂时还是先`git clone`吧

**Comment by forchannot** [comment]
> > 
> 
> 试了，写在`pyproject.toml`中才能读取`site-package`中的包，那只能稍作修改了，暂时还是先`git clone`吧

![image](https://user-images.githubusercontent.com/100580891/177048210-a16f4051-5f25-4710-a14e-1691ed372689.png)
我现在用clone装的打开nonebot会报特别多错，大概看了下基本都是no module named，是因为改了逻辑只加一条nonebot.load_plugins("LittlePaimon")不行了吗，因为报错太多了，不好放过来

**Comment by CMHopeSunshine** [comment]
> > > 
> > 
> > 
> > 试了，写在`pyproject.toml`中才能读取`site-package`中的包，那只能稍作修改了，暂时还是先`git clone`吧
> 
> ![image](https://user-images.githubusercontent.com/100580891/177048210-a16f4051-5f25-4710-a14e-1691ed372689.png) 我现在用clone装的打开nonebot会报特别多错，大概看了下基本都是no module named，是因为改了逻辑只加一条nonebot.load_plugins("LittlePaimon")不行了吗，因为报错太多了，不好放过来

no module named应该只是缺少了我新弄的包`littlepaimon_utils`，pip安装一下这个包就行

**Comment by forchannot** [comment]
> > > > 
> > > 
> > > 
> > > 试了，写在`pyproject.toml`中才能读取`site-package`中的包，那只能稍作修改了，暂时还是先`git clone`吧
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/100580891/177048210-a16f4051-5f25-4710-a14e-1691ed372689.png) 我现在用clone装的打开nonebot会报特别多错，大概看了下基本都是no module named，是因为改了逻辑只加一条nonebot.load_plugins("LittlePaimon")不行了吗，因为报错太多了，不好放过来
> 
> no module named应该只是缺少了我新弄的包`littlepaimon_utils`，pip安装一下这个包就行

07-04 00:21:44 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.Paimon_Plugins.paimon_help, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\nonebot\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File ".\LittlePaimon\Paimon_Plugins\paimon_help.py", line 149, in _
    await help_.finish(draw_help_info(help_info))
  File ".\LittlePaimon\Paimon_Plugins\paimon_help.py", line 92, in draw_help_info
    bg_img = Image.open(str(res_path / 'bg.jpg')).convert('RGBA').resize((1500, total_height))
  File "C:\Users\Administrator\Desktop\nonebot\venv\lib\site-packages\PIL\Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'LittlePaimon\\res\\help\\bg.jpg'
发送help报错，打开的时候提示资源文件检查完毕
![image](https://user-images.githubusercontent.com/100580891/177048499-26e1ca98-a1c5-40cb-88f2-cafa126ddca1.png)

**Comment by forchannot** [comment]
> > 
> 
> 试了，写在`pyproject.toml`中才能读取`site-package`中的包，那只能稍作修改了，暂时还是先`git clone`吧

![image](https://user-images.githubusercontent.com/100580891/177048920-e11048e9-e705-47b8-868c-cd843b91391c.png)
这个里面不仅要添加LittlePaimon，还要添加littlepaimon_utils才行，包括通过clone的要这么做。因为都需要通过pip来装utils这个包

**Comment by CMHopeSunshine** [comment]
> > > 
> > 
> > 
> > 试了，写在`pyproject.toml`中才能读取`site-package`中的包，那只能稍作修改了，暂时还是先`git clone`吧
> 
> ![image](https://user-images.githubusercontent.com/100580891/177048920-e11048e9-e705-47b8-868c-cd843b91391c.png) 这个里面不仅要添加LittlePaimon，还要添加littlepaimon_utils才行，包括通过clone的要这么做。因为都需要通过pip来装utils这个包

help那个改漏了，已改好。这里的话，littlepaimon_utils会作为依赖一起安装，不过倒是提醒了我，git clone要加一句安装requirements.txt

**Comment by CMHopeSunshine** [comment]
现在应该没什么问题了（~~希望如此~~，~~上传pypi真麻烦~~)

**Comment by forchannot** [comment]
> 现在应该没什么问题了（~希望如此~，~上传pypi真麻烦~)

这次又会出现
![image](https://user-images.githubusercontent.com/100580891/177049316-6c9c5394-a104-40f9-a4ad-24079625d49c.png)
，也许是我的问题，但是都是按照教程来的
编辑下，解决了，确实是我的问题
